### ISSUE TITLE
สินค้าในตระกร้าหาย หลังกด ดำเนินการ (ไม่ได้ล็อคอิน) 

### ISSUE THREAD

**Issue by joomlacorner** [topvalue/test_site#1]
เลือกสินค้าเข้าตระกร้า โดยไม่ล็อคอิน 
ให้ทดสอบบนเว็บไซต์  TopValue.xyz

![2f20404c-33b8-11e6-8b92-1acbd8519cf5](https://cloud.githubusercontent.com/assets/144291/16727193/23ea1064-478a-11e6-9f8b-d65ea6aaa8a1.png)

**Comment by wanidagithub** [comment]
ทดสอบซ้ำอีกครั้ง สามารถเพิ่มสินค้าในรถเข็น และคลิก"ดำเนินการชำระเงิน" สำเร็จ 
![image](https://cloud.githubusercontent.com/assets/18567876/17044602/dc2b9fee-4feb-11e6-840d-58e7acbcbad9.png)

**Comment by joomlacorner** [comment]
fixed #1
