### ISSUE TITLE
[Help] อัพโหลดรายการสินค้าที่จะขึ้น Flashsale (Daily Deal) ในแต่ละวัน + จัดเรียงตำแหน่งสินค้า

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#10]
ตัวอย่างที่ใช้กันอยู่ค่ะ
![image](https://cloud.githubusercontent.com/assets/20397170/17163637/94ea776e-53eb-11e6-857f-5676001bbee9.png)

และอยากจะสามารถเรียงสินค้าได้เองค่ะ ตอนนี้ระบบรันลำดับให้อัตโนมัติตาม Product ID ค่ะ

**Comment by jam-krisada** [comment]
@joomlacorner @jintopvalue ยังคิดวิธีการเรียงสินค้าไม่ได้ครับ

**Comment by jam-krisada** [comment]
เขียนระบบ อัพโหลดไฟล์​ CSV เพื่อเพิ่มสินค้าเข้า Extension Daily Deal

**Comment by jam-krisada** [comment]
ไฟล์ Flash Sale ที่พบในเครื่อง production 
sftp://52.77.3.4//usr/share/nginx/html/shell/flash_sale.php
[flash_sale.zip](https://github.com/topvalue/test_site/files/453978/flash_sale.zip)

**Comment by jam-krisada** [comment]
ตัวอย่างไฟล์ Flash_sale ต้นแบบครับ
[flash_sale.xlsx](https://github.com/topvalue/test_site/files/454463/flash_sale.xlsx)
1. อัพโหลดไฟล์ด้วย FTP Client ไปยัง /var/import/
![screen shot 2559-09-05 at 1 44 40 pm](https://cloud.githubusercontent.com/assets/19877215/18239345/ec46f652-736e-11e6-908c-980952e3a2ec.png)
2.การเพิ่มสินค้าเข้ากิจกรรม จะต้อง Login ระบบหลังบ้าน Magento ก่อน ครับ
3. วิธีการเพิ่มสินค้าเข้ากิจกรรม ให้เลือกไฟล์ที่อัพโหลดไว้ กดปุ่ม Submit
http://www.topvalue.xyz/flash_sale.php
![screen shot 2559-09-05 at 1 43 02 pm](https://cloud.githubusercontent.com/assets/19877215/18239314/b2a5fbc8-736e-11e6-992c-9833b5cbd087.png)
4. ระบบจะดำเนินการเพิ่มสินค้าไปยังระบบ สามารถเช็คสินค้าได้ที่ ระบบ DailyDeal
![Uploading Screen Shot 2559-09-05 at 1.46.22 PM.png…]()

@joomlacorner @jintopvalue ขั้นตอนจะเป็นตามนี้ครับ กำลังเขียนโปรแกรม import ให้อยู่ครับ

**Comment by jam-krisada** [comment]
เขียนและทดสอบเรียบร้อยแล้วครับ 
เรื่องการจัดเรียงต้องได้เงื่อนไขที่ชัดเจนการในเรียงเช่น จาก ราคา, ชื่อ, วันที่กิจกรรมจะหมดอายุ ครับ
ซึ่งสามารถปรับได้ในส่วนของการแสดงผลครับ 
@jintopvalue @joomlacorner

**Comment by jintopvalue** [comment]
@jam-krisada 
กำหนดการแสดงผลได้จากตรงไหนเหรอคะ เช่น อยากจะให้เรียงจาก วันที่กิจกรรมจะหมดอายุ ค่ะ

**Comment by jam-krisada** [comment]
เดิมที่ไม่มีการตั้งค่าใน Extension นี้ว่าจะให้เรียงจากอะไรครับผม
@jintopvalue แจ้งความต้องการแล้วผมเขียน code ให้เป็นไปตามที่ต้องการครับ ไม่มีส่วน config ให้ user ปรับแต่งค่าครับ

**Comment by jintopvalue** [comment]
@jam-krisada เรียงให้สินค้าที่จะหมดช่วงเวลากิจกรรมขึ้นก่อนค่า
