### ISSUE TITLE
[Bug] ใส่ Affiliate Coupon แล้วขึ้นเป็นหน้าขาว

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#12]
Test Case: TVL_AF_001 [https://docs.google.com/spreadsheets/d/1LFSn-5S9TcoOOvrx3Wq8UHD2AvpXKw9EfeUy3UXHH60/edit?usp=sharing](url)
ถ้าเป็น Coupon ที่ไม่ตรงเงื่อนไข จะขึ้น error ปกติ
![image](https://cloud.githubusercontent.com/assets/20397170/17165713/943aa832-53fc-11e6-9a57-ac80af9cdca1.png)

แต่ถ้าเป็น coupon ที่ตรงเงื่อนไข จะค้างที่หน้า checkout/cart 
![image](https://cloud.githubusercontent.com/assets/20397170/17165724/a18480e4-53fc-11e6-8c69-b3bb121b26ba.png)

**Comment by jam-krisada** [comment]
@jintopvalue เช็คแล้วครับ เรียบร้อยครับ
<img width="1257" alt="da692634-6415-11e6-9682-d888f316c355" src="https://cloud.githubusercontent.com/assets/19877215/17771550/c9a29cc8-656d-11e6-8694-b44f49a38475.png">

<img width="443" alt="e23b20d8-6415-11e6-970b-d480ad1a24fd" src="https://cloud.githubusercontent.com/assets/19877215/17771558/d36976e6-656d-11e6-9afa-c54950fa1266.png">

cc : @joomlacorner
