### ISSUE TITLE
[Help] รูปสินค้าในหน้า Gallery ไม่ชัดเท่าหน้า Homepage

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#13]

**Comment by jam-krisada** [comment]
ปรับความคมชัดของภาพแล้วครับ

ตัวอย่างรูปหน้าสินค้า
http://www.topvalue.xyz/banana-boat-ultra-sport-sunscreen-lotion-spf50-pa.html
![screen shot 2559-07-27 at 6 50 53 pm](https://cloud.githubusercontent.com/assets/19877215/17174354/271e7362-542b-11e6-8f87-aab50e36e5cc.png)

ตัวอย่างรูปหน้าหมวดหมู่สินค้า
http://www.topvalue.xyz/--37/-1.html
![screen shot 2559-07-27 at 6 51 14 pm](https://cloud.githubusercontent.com/assets/19877215/17174379/49dc6c42-542b-11e6-9ffc-b39e6a3b13bd.png)

ตัวอย่างรูปหน้าผลการค้นหา
http://www.topvalue.xyz/catalogsearch/result/?q=banana
![screen shot 2559-07-27 at 6 51 25 pm](https://cloud.githubusercontent.com/assets/19877215/17174390/58e95786-542b-11e6-9ef3-927f07a1cb26.png)

solved #13
