### ISSUE TITLE
[New Feature] ถ้ายังชำระเงินไม่สำเร็จ Coupon code จะไม่เสีย

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#14]
เวลาลูกค้าใส่ coupon code กดยืนยันไปแล้ว 
แต่ชำระเงินไม่สำเร็จ (เน็ตหลุด, error, เด้งออก, ปิดหน้าเว็บ ฯลฯ) ทำให้คูปองนั้นเสียไปเลยโดยที่ยังไม่ได้ใช้
ทาง CS ต้องมาเจนรหัสใหม่ให้

**Comment by joomlacorner** [comment]
เนื่องจากชำระเงินไม่สำเร็จ แล้วมี Sale Order เกิดขึ้นแล้วครับ  
ตัวระบบคูปองมันจึงจำเป็นต้องตัดว่ามีการใช้

**Comment by jam-krisada** [comment]
ยกเลิก
