### ISSUE TITLE
[New Feature] Extension Admin Action Log 

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#15]
เปิดใช้งาน extension

**Comment by jam-krisada** [comment]
@jintopvalue @joomlacorner ติดตั้งและตรวจสอบการใช้งานเรียบร้อยแล้วครับ
![screen shot 2559-08-25 at 1 19 47 pm](https://cloud.githubusercontent.com/assets/19877215/17958878/054bb558-6ac7-11e6-880b-6c21f9ec6945.png)
![screen shot 2559-08-25 at 1 21 21 pm](https://cloud.githubusercontent.com/assets/19877215/17958890/11990aae-6ac7-11e6-98d8-1aa3554b3096.png)
![screen shot 2559-08-25 at 1 21 48 pm](https://cloud.githubusercontent.com/assets/19877215/17958897/17e60682-6ac7-11e6-9832-376d50403632.png)
![screen shot 2559-08-25 at 1 21 59 pm](https://cloud.githubusercontent.com/assets/19877215/17958905/233862d2-6ac7-11e6-8cb8-d7c56c542b80.png)
![screen shot 2559-08-25 at 1 22 20 pm](https://cloud.githubusercontent.com/assets/19877215/17958914/27b1a7a6-6ac7-11e6-9468-05886425a65b.png)
