### ISSUE TITLE
[Bug] Report บน Magento ข้อมูลไม่ตรงกับความจริง

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#16]
ข้อมูลน้อยกว่าความเป็นจริงๆ บางฟังก์ชั่นอย่าง Most viewed ก็ขึ้น No records Found
![image](https://cloud.githubusercontent.com/assets/20397170/17166340/9794ea70-5400-11e6-897a-ab78a58d1599.png)

**Comment by jam-krisada** [comment]
จากการตรวจสอบ พบว่าข้อมูลยังไม่ได้กดอัพเดท Refresh Stat ครับ

![screen shot 2559-07-27 at 7 05 04 pm](https://cloud.githubusercontent.com/assets/19877215/17174732/b6a8ff1e-542d-11e6-9ef2-99da51aee5ad.png)

**Comment by jintopvalue** [comment]
ตั้งให้ Most viewed refresh อัตโนมัติเหมือนรายการอื่นๆได่ไหมคะ
แล้วถ้ากด refresh statistics for the last day จะทำให้เว็บค้างไหมคะ?

**Comment by jam-krisada** [comment]
@jintopvalue การ Refresh Statistics จะต้องทำ Manual เท่านั้นครับ จากภาพอาจมีคน refresh ช่องอื่นไปพร้อมกันแต่ไม่ได้ refresh Most Viewed ครับ ทำผ่านหน้าเว็บปกติ Server จะกำหนดเวลาประมวลผลไว้ครับ มันจะหยุดประมวลผลเองถ้าหมดเวลา เช่น ตั้งไว้ 30s จะไม่ส่งผลให้เครื่องช้าครับ
