### ISSUE TITLE
[New Feature] Internet Banking 

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#18]
อันนี้เหมือนจะต้องเริ่มใหม่ตั้งแต่ต้นเลยค่ะ 
![image](https://cloud.githubusercontent.com/assets/20397170/17166527/a75b6f82-5401-11e6-8e11-38ed5416b3d9.png)
[How to connecting Modern pay API-TH_v1.3 (1).pdf](https://github.com/topvalue/test_site/files/385463/How.to.connecting.Modern.pay.API-TH_v1.3.1.pdf)

**Comment by jam-krisada** [comment]
ยกเลิก
