### ISSUE TITLE
[Bug] เวลาแก้ description หรือชื่อสินค้า ต้องแก้ทั้งที่ Store view: English และไทย

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#19]
เวลาแก้ข้อมูลสินค้า แก้ที่ Store View: default Value แล้วค่าไม่เปลี่ยน  เพราะระบบไม่ติ๊กช่อง Use default Value ให้แต่แรก ต้องมาติ๊กเองหรือต้องตามแก้ที่ Store view: English กับ ไทย ด้วย

![image](https://cloud.githubusercontent.com/assets/20397170/17166638/72b09ed2-5402-11e6-851b-d262eebe863a.png)

**Comment by joomlacorner** [comment]
ลองใน  topvalue.xyz  แล้วไม่เป็นปัญหาครับ  ระบบมัน Default เลือกไว้ครับ
