### ISSUE TITLE
ค่าขนส่งไม่ขึ้นให้เลือก EMS

### ISSUE THREAD

**Issue by jam-krisada** [topvalue/test_site#2]
ค่าขนส่งไม่ขึ้นให้เลือก EMS แสดงเพียงแต่ Kerry และ Yamato
ตัวอย่างที่ถูกต้อง
![a2436fa6-42b6-11e6-868e-55e879e2e50c](https://cloud.githubusercontent.com/assets/19877215/16754012/d941b46a-4818-11e6-961c-24d47f0dcf52.png)

![b92fbc42-42b6-11e6-8048-2e32363abe95](https://cloud.githubusercontent.com/assets/19877215/16754020/ddfe9a86-4818-11e6-9ff5-91625b2d3ad5.png)

**Comment by wanidagithub** [comment]
ทดสอบสั่งซื้อสินค้า 1 ชิ้น ราคา 345 บาท (ไม่ได้ login)
ค่าขนส่งขึ้น EMS ให้เลือกแล้ว
![image](https://cloud.githubusercontent.com/assets/18567876/17044707/b7fa0e98-4fec-11e6-91dc-4cf725a8020b.png)

**Comment by joomlacorner** [comment]
fixed #2
