### ISSUE TITLE
[Bug] ย่อลิงค์ใน Bitly ไม่ได้ 

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#20]
ลิงก์ที่ย่อมาจาก bitly ไม่ยอมกางออกเป็นลิงก์เต็มๆให้ เช่น topvalue.me/Smtope พอก๊อปวางก็เข้า www.topvalue.com/Smtope เลย ทำให้หน้า error

![image](https://cloud.githubusercontent.com/assets/20397170/17166672/aa47b5ce-5402-11e6-92b2-ae775d3592ba.png)

![image](https://cloud.githubusercontent.com/assets/20397170/17166684/b91877fa-5402-11e6-8d20-a4fbb36c3e6a.png)

**Comment by joomlacorner** [comment]
@jintopvalue  ขอพี่เช็คกับ @koobitor  ก่อนว่า topvalue.me คืออะไร  ทำงานอย่างไร

**Comment by jam-krisada** [comment]
@joomlacorner @jintopvalue 
topvalue.me redirect ไป topvalue.com น่าจะไม่มีข้อมูลอะไรอยู่แล้วครับ
พอไม่มีข้อมูลและโดย redirect ไป .com ก็ไม่สามารถ redirect ต่อไปยัง url ที่ตั้งไว้ได้ครับ
เพราะข้อมูล short url น่าจะต้องอยู่ใน topvalue.me
