### ISSUE TITLE
[New Feature] Extension Reward Point

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#23]
เปิด Extension Reward Point

**Comment by jam-krisada** [comment]
@jintopvalue อันนี้เปิดใช้งานแล้วอาจจะต้องดูเงื่อนไขการให้ Point ครับ
![screen shot 2559-08-18 at 6 00 00 pm](https://cloud.githubusercontent.com/assets/19877215/17771518/9e46702c-656d-11e6-9aec-fa30e1292425.png)

**Comment by jintopvalue** [comment]
@jam-krisada ลองกำหนด earning rules จาก category เพื่อทดสอบแล้ว ขึ้น Error นี้ค่ะ 
![image](https://cloud.githubusercontent.com/assets/20397170/18340786/1fc9c108-75d1-11e6-8867-3d685fd4dc6d.png)

ไม่แน่ใจเกี่ยวกับเรื่องที่ต้องสร้าง cronjobs ไหมอ่ะค่ะ
http://www.mage-world.com/wiki/index.php?title=RewardPointsPro-user-guide
![image](https://cloud.githubusercontent.com/assets/20397170/18340803/3838f934-75d1-11e6-93ae-aa93551fb94a.png)

**Comment by jam-krisada** [comment]
ผมรบกวนช่วย capture step ที่ทำให้เกิด error ให้หน่อยครับ
@jintopvalue @oopbest

**Comment by jintopvalue** [comment]
@jam-krisada 
1. ไปที่ Catalog Earning Rules และเลือก Add new Rule ค่ะ
![image](https://cloud.githubusercontent.com/assets/20397170/18342259/18ef5a8a-75d8-11e6-9127-c8b21cc13901.png)
2. กรอก Rule information และ Action
![image](https://cloud.githubusercontent.com/assets/20397170/18342273/312bb1c0-75d8-11e6-8279-af61021e91f8.png)
![image](https://cloud.githubusercontent.com/assets/20397170/18342274/33d461a6-75d8-11e6-8b59-eb05a96ae72f.png)

3. กรอก Conditions กด Save and Apply
![image](https://cloud.githubusercontent.com/assets/20397170/18342290/420cdfa0-75d8-11e6-9d32-1f4b294a93bc.png)

4. ขึ้น Error ค่ะ
![image](https://cloud.githubusercontent.com/assets/20397170/18342295/49527964-75d8-11e6-9271-dd276ef7a726.png)

**Comment by jintopvalue** [comment]
@jam-krisada 
ปุ่มsubmitกับดาวเบี้ยวค่ะ
![image](https://cloud.githubusercontent.com/assets/20397170/18344938/8c22fcc2-75e3-11e6-8aa4-398588c656b1.png)

**Comment by jam-krisada** [comment]
@jintopvalue ทดสอบในเครื่อง Dev ไม่ขึ้น error ครับ
น่าจะเป็นที่ config server กำลังดูให้นะครับ
![screen shot 2559-09-08 at 6 30 20 pm](https://cloud.githubusercontent.com/assets/19877215/18347884/6913c414-75f2-11e6-9326-0a8474a1cccb.png)

**Comment by jam-krisada** [comment]
@jintopvalue themes ให้แล้วครับผม
![screen shot 2559-09-08 at 6 41 30 pm](https://cloud.githubusercontent.com/assets/19877215/18348180/152abc84-75f4-11e6-95d5-88e93e7afe7b.png)
![screen shot 2559-09-08 at 6 39 11 pm](https://cloud.githubusercontent.com/assets/19877215/18348181/155b004c-75f4-11e6-95c8-4a77a8572db0.png)
