### ISSUE TITLE
[New Feature] Extension แจ้งเตือนเมื่อมีสินค้า

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#24]
เปิด Extension แจ้งเตือนเมื่อมีสินค้า (รู้สึกจะเป็นแบบฟรีนะคะ ที่พี่ต่อโหลดเพิ่มมา) แบบเดิมที่มีอยู่ใช้ค่อนข้างยาก
แบบที่โหลดมาคือแค่กรอกอีเมลน่ะค่ะ

**Comment by jam-krisada** [comment]
@jintopvalue ผมไม่แน่ใจว่า Extension ตัวไหนนะครับ จากการทดสอบการใช้งานเดิมที่มีมากับ magento เพียงลูกค้าสมัครสมาชิกก็จะกด ติดตามสถานะได้ทันที
ทดสอบการใช้งานที่ http://www.topvalue.xyz/1127725712021-the-balm-instain.html

![screen shot 2559-08-05 at 4 21 34 pm](https://cloud.githubusercontent.com/assets/19877215/17432301/bb9499dc-5b28-11e6-913a-ffbc7f81d944.png)

![screen shot 2559-08-05 at 4 13 41 pm](https://cloud.githubusercontent.com/assets/19877215/17432105/a28cacbe-5b27-11e6-9ede-78a2a081fcb7.png)

![screen shot 2559-08-05 at 4 21 27 pm](https://cloud.githubusercontent.com/assets/19877215/17432316/c910842c-5b28-11e6-9ada-b1fa072dc515.png)

**Comment by jintopvalue** [comment]
@jam-krisada ปรึกษากับทีมแล้ว สรุปว่าฟังก์ชันเดิมที่มีมากับ magento โอเคอยู่แล้วค่ะ ใช้แบบนี้ไปก็ได้
แต่สงสัยนิดนึงค่ะ ข้อความ Signup to get notified สามารถเปลี่ยนเป็นรูปปุ่มได้ใช่ไหมคะ

**Comment by jam-krisada** [comment]
@jintopvalue สามารถเปลี่ยนเป็นรูปปุ่มได้ครับ ส่งมาได้เลยครับ

**Comment by jintopvalue** [comment]
@jam-krisada ทีมกราฟฟิคบอกว่า ในเว็บเดิมปุ่ม add to cart, แจ้งเตือนเมื่อมีสินค้า เขียนด้วยโค้ดน่ะค่ะ
ไม่ทราบว่าใช้โค้ดกับรูปมีผลต่างกันไหมคะ

**Comment by jam-krisada** [comment]
@jintopvalue ไม่ต่างกันครับ เพียงการแสดงผลเฉยๆครับ

**Comment by jintopvalue** [comment]
@jam-krisada  รูปปุ่มค่ะ
![notification button-01](https://cloud.githubusercontent.com/assets/20397170/17802369/24552f6c-661a-11e6-9d36-3d6360956fb2.png)

**Comment by jam-krisada** [comment]
@jintopvalue เปลี่ยนเป็นรูปให้แล้วครับ
![screen shot 2559-08-25 at 1 46 52 pm](https://cloud.githubusercontent.com/assets/19877215/17959409/696863b2-6aca-11e6-9bb2-8c777d827cb4.png)
