### ISSUE TITLE
Elastic Search

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#27]
จินลองจากคำที่มีการ search เยอะๆ บน .com นะคะ

1) "ครีม" ขึ้นตัวเลือกสี ก่อนชื่อสินค้า อยากแสดงผลเป็นสินค้าก่อนค่ะ
![image](https://cloud.githubusercontent.com/assets/20397170/17319913/03096420-58bb-11e6-80e1-8ddf2c329f0c.png)
  
2) "Note 5" แสดงผลทุกสินค้าที่มีเลข 5  
![image](https://cloud.githubusercontent.com/assets/20397170/17320519/29a1d574-58be-11e6-8e67-98f713722c0a.png)

3) "จักรยาน" แสดงผลเป็นแว่นกันแดด
![image](https://cloud.githubusercontent.com/assets/20397170/17320521/34f81172-58be-11e6-8fc4-8f92688a344a.png)

4) "g shock" แสดงผลไม่ตรง
![image](https://cloud.githubusercontent.com/assets/20397170/17320534/44da59ec-58be-11e6-9c45-ab80249f1d12.png)

5) "iphone" พวกเคส สายชาร์จ อุปกรณ์เสริมขึ้นมาก่อนโทรศัพท์ อยากให้โทรศัพท์ขึ้นก่อนค่ะ 
6) "มือถือ" แสดงผลเป็นพวก ที่ปอกกระเทียมมือถือ ที่ปอกแตงกวามือถือ แต่ไม่ขึ้นโทรศัพท์มือถือ
7) ถ้าไม่มี space bar จะหาของไม่เจอ "Power Bank" แสดงผลถูกต้อง แต่ "Powerbank" หาไม่เจอ "Wet n wild" หาเจอ แต่ "Wetnwild"หาไม่เจอ
8) keyword ที่น้อยกว่า 4 ตัวอักษรจะหาไม่เจอ พวกรุ่นมือถือและสินค้าบางยี่ห้อจะมีไม่ถึง 4 ตัวค่ะ ทำให้หาไม่ได้เลย บางทีกด space bar หลังชื่อ ก็เสิร์ชเจอ บางทีเสิร์ชไม่เจอค่ะ เช่น dhc + space bar เจอค่ะ แต่ nyx + space bar ไม่เจอค่ะ 
![image](https://cloud.githubusercontent.com/assets/20397170/17320305/1fffd990-58bd-11e6-8860-e96c5a97ac81.png) 
![image](https://cloud.githubusercontent.com/assets/20397170/17320314/2a318a1c-58bd-11e6-8c0d-0a60781a02a9.png)

9) เรื่อง "-" SP-303 เสิร์ชไม่เจอ เพราะหน้าเว็บ เป็น SP303 สินค้าที่แสดงผลบางตัวก็ไม่มี 303 
![image](https://cloud.githubusercontent.com/assets/20397170/17320362/678816f6-58bd-11e6-8acd-b37a2cd44e70.png)

HO-0212 กับ  HO0212 แสดงผลต่างกัน มี - หรือไม่มี - ให้มีค่าเท่ากันได้ไหมคะ
![image](https://cloud.githubusercontent.com/assets/20397170/17320396/8cec4034-58bd-11e6-9d9b-21a15a4f0825.png)
![image](https://cloud.githubusercontent.com/assets/20397170/17320416/a9464ca2-58bd-11e6-93b0-a4c5e93fe682.png)

**Comment by jam-krisada** [comment]
สรุปจากด้านบนครับ
1) ต้องการให้สินค้าครีมขึ้นก่อนสินค้าอื่นๆ
2) อยากให้ค้นหาคำว่า "Note 5" ขึ้นแต่สินค้า Note 5 เท่านั้น
3) ไม่อยากให้ คำที่อยู่ใน Description มีผลต่อการค้นหา
![screen shot 2559-08-02 at 2 40 16 pm](https://cloud.githubusercontent.com/assets/19877215/17320710/18698166-58bf-11e6-810a-828377fdfd18.png)
4) คำว่า g sock ไม่ขึ้นสินค้า G-Shock เลย
5) สินค้าราคาแพงควรขึ้นก่อน
6) ควรแสดงสินค้าในหมวดหมู่ มือถือ
7) อยากให้ติดหรือแยกคำก็ค้นหาได้
8) อยากให้จำนวนการค้นหาขั้นต่ำเป็น 3 อักษร
9) อยากให้แสดงผลเหมือนกันระหว่าง มี ขีดและไม่มีขีด

**Comment by thangman22** [comment]
1,6) เรื่องหมวดหมู่ที่ตรงอาจจะค่อนข้างยากหน่อยครับ เพราะระบบไม่ทราบว่า keyword นี้อยู่หมวดอะไรยกเว้นว่าจะ Pre define ไว้ก่อนทั้งหมด หรือ อาจจะต้อง ใส่ tag ของสินค้าแล้ว search จากตรงนั้นเป็นหลักครับ
2-3) น่าจะแก้ปัญหาด้วยการ Description ออกจาก ผลการค้นหา
4,9) เดี๋ยวจะลองแก้เรื่อง symbol ให้ครับ
5) อันนี้ไม่มีปัญหาครับ
7) ได้ครับ
8) ได้ครับ

**Comment by jam-krisada** [comment]
@jintopvalue อันนี้อธิบายเพิ่มเติมครับ
1) ตอนนี้ตั้งค่าเรียงจากราคาถูกไปราคาสูงครับ อันนี้ถูกต้องหรือไม่ครับ
2) หากต้องการค้นหา ทั้งคำ จะต้องใช้ "note 5" แทนการพิมพ์​ note 5 เฉยๆ ครับ 
![screen shot 2559-08-02 at 3 02 38 pm](https://cloud.githubusercontent.com/assets/19877215/17321344/435e0da8-58c2-11e6-82e2-e5706e274e16.png)
3) เพื่อให้ความเป็นไปได้ในการค้นหาสินค้าเพิ่มมากขึ้น ตอนนี้สิ่งที่นำมา คำนวณ จะเป็น ชื่อและรายละเอียดสินค้าครับ

**Comment by thangman22** [comment]
ตอนนี้หลักๆที่มีปัญหาเพราะมาจากเราเอา รายละเอียดไม่รวมในผลการค้นหาครับ

**Comment by joomlacorner** [comment]
@jintopvalue  
ข้อ 1. กับ 6  คล้ายกัน  ถ้า user ใส่แค่คำว่า ครีม  รู้ได้อย่างไรว่าเขาไม่ได้หา สี  เพราะถ้าพิมพ์แค่คำเดี่ยวๆ แล้วระบบค้นหาสิ้นค้าได้ทั้งเว็บว่ามีคำว่า ครีม อยุ่ตรงไหนบ้าง มาแสดงได้ ในเวลาอันรวดเร็ว  เมื่อลูกค้าเห็นผลลัพธ์ ปกติเขาก็จะกรอง ใส่คำเจาะจงลงไป หาสินค้าที่ต้องการครับ

ข้อ 2-3 ถ้าระบบการ Search ไม่ค้นจาก Description  จะ ok ?    โดยส่วนตัวเห็นว่ายิ่งค้นหาได้ละเอียดมากเท่าไหร่ ก็ดีกับ user ที่กำลังหาสินค้าอยู่ครับ และการอัพเดดสินค้าก็จะยืดหยุ่นกว่าที่จะไว้ในชื่อสินค้าอย่างเดียว 

ส่วนการแสดงผล ที่ตอนนี้เป็นราคาถูกขึ้นก่อน หากจะเปลี่ยนเป็นแพงสุดขึ้นก่อน รีบแจ้งครับ ซึ่งตอนที่กำหนดให้เอาราคาถูกขึ้นก่อนคิดว่าคงมีเหตุผลอยู่ครับที่ไม่อยากให้ user รู้สึกว่าที่นี่มีแต่สินค้าราคาแพง

**Comment by jintopvalue** [comment]
@jam-krisada @thangman22 @joomlacorner 

ถ้าจะให้พิมพ์ keyword ไปแล้ว ขึ้นว่าจะดูผลการค้นหาของหมวดไหน แบบนี้ได้ไหมคะ น่าจะ scope แคบลงเยอะค่ะ 
ใน dropdown ต่อจากผลการค้นหาตามหมวด ก็แสดงสินค้าที่ 1) ชื่อสินค้าตรงตาม keyword (ถ้าชื่อสินค้าไม่ตรง ไปดู description แทน) 2) เรียงจากยอด view มากไปน้อย

![image](https://cloud.githubusercontent.com/assets/20397170/17322964/36e6387c-58ca-11e6-92c5-133d24154805.png)

**Comment by jintopvalue** [comment]
@jam-krisada @thangman22 @joomlacorner

เรื่อง symbol ถ้าจะให้พวก เครื่องหมาย & / ( ) . และ space bar พวกนี้ ไม่มีผลต่อการค้นหา จะมีผลเสียอะไรไหมคะ เพราะส่วนใหญ่จะหาไม่เจอกันเพราะ symbol ขาดหรือเกินไปน่ะค่ะ

**Comment by jintopvalue** [comment]
@joomlacorner 
1) ถ้าชื่อยาวๆ จะอยู่คนละบรรทัดกับรูปอ่ะค่ะ อยากให้ชื่อยาวได้เต็มที่ 2 บรรทัดค่ะ เกินจากนั้นก็เป็น ... ไปค่ะ ไม่อยากให้เกินมาช่องอื่นค่ะ
2) ตรง "ราคา 230.00 บาท" ปรับให้เหลือเป็น "230.00 บาท" เป็นตัวหนาและเป็นสีแดง topvalue ได้ไหมคะ 
![image](https://cloud.githubusercontent.com/assets/20397170/17662842/a76fc6e2-6312-11e6-8824-3002b671ac66.png)

**Comment by jam-krisada** [comment]
@jintopvalue 1) ปรับให้เหลือ 2 บรรทัดแล้วครับ
2) ลบคำว่าราคาออกและปรับเป็นสีแดงแล้วครับ ทศนิยมเนื่องจากเห็นว่าสินค้าไม่มีทศนิยมจึงตัดส่วนนี้ออกไปครับ
![screen shot 2559-08-16 at 5 04 21 pm](https://cloud.githubusercontent.com/assets/19877215/17695708/0abd7444-63d4-11e6-9978-b8065d8bbe3b.png)

cc : @joomlacorner

**Comment by jintopvalue** [comment]
@jam-krisada จินลองแล้วยังเจอว่ารูปกับชื่อไม่ตรงกันค่ะ 
![image](https://cloud.githubusercontent.com/assets/20397170/17727068/fb97e046-6480-11e6-9497-d5beb6c0d388.png)

**Comment by jintopvalue** [comment]
@jam-krisada ในส่วนของ elasticsearch อยากให้
1) สามารถเสิร์ชด้วยหมายเลข SKU ได้เหมือนกับใน .com ค่ะ
2) กรอบผลการค้นหาแสดงผลค้างอยู่ จนกว่าจะกดนอกกรอบค่ะ เพราะเผลอเลื่อนเม้าส์หลุดไปนิดเดียวกรอบก็หายไปแล้วค่ะ ใช้ค่อนข้างยากค่ะ

**Comment by jam-krisada** [comment]
@jintopvalue 
1 ) กำลังปรับแก้ไขให้อยู่ครับ
2) ปรับแก้ไขให้แล้วครับ

**Comment by jam-krisada** [comment]
@jintopvalue เพิ่มการค้นหา sku แล้วครับ
<img width="1030" alt="screen shot 2559-08-18 at 11 24 40 pm" src="https://cloud.githubusercontent.com/assets/19877215/17781814/0c04db94-659b-11e6-9fac-021ee853344d.png">


cc : @joomlacorner

**Comment by jintopvalue** [comment]
@jam-krisada ทีมลงสินค้าได้ลองสร้าง item ชื่อ "OTTO เตาย่างเกาหลี รุ่น GR-175 (เทส)" SKU: "1115942457443" แต่เสิร์ชไม่เจอค่ะ ไม่ทราบว่าเป็นเพราะล็อคไม่ให้สร้างไอเทมจากฝั่ง MGT หรือเปล่าคะ?

**Comment by jam-krisada** [comment]
@jintopvalue ระบบอัพเดทสินค้าไปยัง Elastic Search ยังไม่เสร็จครับผม
ตอนนี้จะเป็นการยิงเข้าเครื่อง Search เป็นรอบๆไปครับ

**Comment by jam-krisada** [comment]
***ตรวจสอบผลการค้นหา ES ในหน้า Result Search

**Comment by jam-krisada** [comment]
ยิงราคา Flash Sale เข้าไปในระบบ Search

**Comment by jam-krisada** [comment]
เรียบร้อยแล้วครับ เมื่อสินค้าเข้ากิจกรรม ราคาจะถูกยิงอัพเดทไปยัง ES เอง เมื่อจบกิจกรรม ก็จะยิงไปอัพเดทเป็นราคาปกติเองเช่นกันครับ

**Comment by jintopvalue** [comment]
@jam-krisada 
![image](https://cloud.githubusercontent.com/assets/20397170/18301623/1d8d65c2-74fd-11e6-98e7-22814e450228.png)
1) ในช่อง Elastic Search มีจำกัด Key word ในการ search ไหมคะ? ลองเอาชื่อสินค้าแปะไปแล้วไม่แสดงผลเลยอ่ะค่ะ
2) Hot Keywords (ไฮไลท์เหลือง) สามารถกำหนดได้จากที่ไหนคะ?

**Comment by jam-krisada** [comment]
1) เดี๋ยวผมแก้ไขให้นะครับ ค้นหาได้ตามที่ต้องการครับ
2) อยู่ใน cms -> static block
<img width="1402" alt="screen shot 2559-09-07 at 1 52 04 pm" src="https://cloud.githubusercontent.com/assets/19877215/18302464/50cf4d42-7502-11e6-966a-f22f8f1cb170.png">

**Comment by jam-krisada** [comment]
@jintopvalue 
1) แก้ไขให้แล้วครับ
<img width="919" alt="screen shot 2559-09-07 at 2 12 01 pm" src="https://cloud.githubusercontent.com/assets/19877215/18303012/1fda5a26-7505-11e6-8e0f-f6319f7f60b6.png">

**Comment by jintopvalue** [comment]
@jam-krisada 
ตอนนี้บน .xyz ใช้ elasticsearch ไม่ได้ ไม่ทราบว่าสามารถทดสอบได้ทีไหนคะ
