### ISSUE TITLE
[Fix] ตัวเลือกเป็น dropdown ค่ะ

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#28]
ใน .xyz option เป็น dropdown ค่ะ อยากให้เป็นสีเหมือน .com ค่ะ
![image](https://cloud.githubusercontent.com/assets/20397170/17320670/f0e9b7dc-58be-11e6-86aa-05b26fb681d0.png)

![image](https://cloud.githubusercontent.com/assets/20397170/17320721/258d0872-58bf-11e6-8fdf-2dbae54c75e3.png)

**Comment by jam-krisada** [comment]
แก้ไขให้แล้วครับ
![screen shot 2559-08-02 at 4 21 37 pm](https://cloud.githubusercontent.com/assets/19877215/17323684/3a9c0ee4-58cd-11e6-84db-e3df92e7378d.png)

**Comment by jam-krisada** [comment]
@jintopvalue แก้ไขแล้วครับผม

**Comment by jintopvalue** [comment]
ขอบคุณค่ะ
