### ISSUE TITLE
[Fix] ราคาสินค้าไม่ถึง 1,000 ไม่สามารถเก็บเงินปลายทางได้

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#29]
ถ้ายอดรวมของสินค้าไม่ถึง 1000 บาท จะต้องเลือกเก็บเงินปลายทางไม่ได้ค่ะ

![image](https://cloud.githubusercontent.com/assets/20397170/17325899/4a75f0cc-58d8-11e6-83b2-f358892f45e4.png)

**Comment by jam-krisada** [comment]
@jintopvalue ราคาสินค้าไม่รวมค่าจัดส่งต้องมากกว่าหรือเท่ากับ 1000 บาท ใช้ไหมครับ

**Comment by jam-krisada** [comment]
@jintopvalue แก้ไขแล้วครับ หากราคาสินค้าร่วมไม่เกิน 1000 บาท จะไม่สามารถเลือกเก็บเงินปลายทางได้ครับ
![screen shot 2559-08-03 at 1 26 38 pm](https://cloud.githubusercontent.com/assets/19877215/17355893/1f14aac6-597e-11e6-904b-337675aedf56.png)

**Comment by jam-krisada** [comment]
@joomlacorner แก้ไขแล้วครับ

**Comment by jintopvalue** [comment]
@jam-krisada 
รบกวนปรับให้มีรูปแบบและคำบรรยายเหมือน .com ทีค่ะ 
![image](https://cloud.githubusercontent.com/assets/20397170/17424564/4b5b5e5a-5aef-11e6-94af-98712d0b8ce0.png)

**Comment by jam-krisada** [comment]
ปรับรูปแบบการแสดงผลแล้วครับ @jintopvalue @joomlacorner 
![screen shot 2559-08-05 at 5 00 28 pm](https://cloud.githubusercontent.com/assets/19877215/17433316/2eb90402-5b2e-11e6-8eb1-7b42072b4690.png)

**Comment by jintopvalue** [comment]
@jam-krisada ลบข้อความ "ไม่สามารถเลือกช่องทางนี้ได้**" ออกทีได้ไหมคะ มันยาวเกินวิธีอื่นๆน่ะค่ะ 
![image](https://cloud.githubusercontent.com/assets/20397170/17469146/e42954d2-5d58-11e6-9ea0-4a5b28cc89e2.png)

**Comment by jam-krisada** [comment]
@jintopvalue เอาออกให้แล้วครับ

cc : @joomlacorner
