### ISSUE TITLE
สินค้า Flashsale มีคนซื้อแล้วแต่ไม่ขึ้นจำนวนผู้ซื้อ

### ISSUE THREAD

**Issue by jam-krisada** [topvalue/test_site#3]
จัดซื้อแจ้งว่ามีลูกค้ากดซื้อเข้ามาแล้ว แต่จำนวนผู้ซื้อยังเป็น 0 อยู่

**Comment by jam-krisada** [comment]
สามารถดูตัวอย่างสินค้า Flash Sales ที่ซื้อแล้ว จำนวนที่แสดงเพิ่มขึ้น
http://www.topvalue.xyz/cute-press-uv-expert-protection-whitening-anti-agin-sunscreen-spf50-pa-30ml.html
![screen shot 2559-07-27 at 6 46 35 pm](https://cloud.githubusercontent.com/assets/19877215/17174306/b479b6f0-542a-11e6-8ab8-57d9dd16d30c.png)

solved #3 #17

**Comment by joomlacorner** [comment]
solved #3
