### ISSUE TITLE
[Small fix] Line Pay เปลี่ยนโลโก้ค่ะ

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#30]
อันนี้เรื่องเล็กๆค่ะ ทาง Line Pay เปลี่ยน Logo ค่ะ มีจุดที่ต้องเปลี่ยน 3 จุดค่ะ จินแนบไฟล์ .ai มาด้วยค่ะ 
1) http://www.topvalue.com/ 
![image](https://cloud.githubusercontent.com/assets/20397170/17326406/5fbcb954-58db-11e6-8572-1a13fe12968e.png)

2) /payment-method
![image](https://cloud.githubusercontent.com/assets/20397170/17326408/652228a2-58db-11e6-98fd-64f774babb5e.png)

3) /checkout/onepage
![image](https://cloud.githubusercontent.com/assets/20397170/17326412/6ba268f4-58db-11e6-9734-7b3e386ce3eb.png)

![screen shot 2559-07-13 at 2 40 51 pm](https://cloud.githubusercontent.com/assets/20397170/17326427/82016550-58db-11e6-9639-0c71f66d890d.png)

[RabbitXLINE_Pay_final-7.zip](https://github.com/topvalue/test_site/files/398506/RabbitXLINE_Pay_final-7.zip)

**Comment by jam-krisada** [comment]
1) เปลี่ยนในส่วนของ Footer แล้วครับ
![screen shot 2559-08-03 at 1 54 34 pm](https://cloud.githubusercontent.com/assets/19877215/17356470/d66cc052-5981-11e6-99b5-0510bf9107a8.png)

**Comment by jam-krisada** [comment]
3) แก้ไขในหน้า checkout แล้วครับ
![screen shot 2559-08-03 at 3 11 26 pm](https://cloud.githubusercontent.com/assets/19877215/17358531/a45d498c-598c-11e6-89e4-f282af8551e9.png)

**Comment by jam-krisada** [comment]
2) ปรับให้แล้วครับ ในหน้า วิธีการชำระเงิน
![screen shot 2559-08-03 at 3 20 55 pm](https://cloud.githubusercontent.com/assets/19877215/17358799/f3bc6f5c-598d-11e6-923a-31562896487c.png)

**Comment by jam-krisada** [comment]
@jintopvalue @joomlacorner แก้ไขให้ครบแล้วครับ ตรวจสอบได้ที่ www.topvalue.xyz ครับ

**Comment by jintopvalue** [comment]
รบกวนอีกนิดค่ะ ช่วยเปลี่ยนชื่อเป็น Rabbit LINE Pay ให้ด้วยค่ะ  

![Uploading image.png…]()

![image](https://cloud.githubusercontent.com/assets/20397170/17361790/699c06d4-599c-11e6-850a-e118d5222fa4.png)

**Comment by jam-krisada** [comment]
@jintopvalue  เปลี่ยนให้แล้วครับ
![screen shot 2559-08-04 at 11 17 43 am](https://cloud.githubusercontent.com/assets/19877215/17390464/8bfbc4c6-5a37-11e6-84ea-2ee593f105b5.png)

**Comment by jintopvalue** [comment]
@jam-krisada ขอโทษค่ะ คอมเม้นท์ที่แล้ว รูปมันโหลดไม่ขึ้น มีในหน้าชำระเงินด้วยค่ะ
![image](https://cloud.githubusercontent.com/assets/20397170/17392010/aba5e178-5a44-11e6-84bc-10c15028ce06.png)

**Comment by jam-krisada** [comment]
@jintopvalue แก้ไขแล้วครับ
![screen shot 2559-08-04 at 2 11 57 pm](https://cloud.githubusercontent.com/assets/19877215/17393371/7742918e-5a4d-11e6-9bff-f211d592030f.png)

**Comment by joomlacorner** [comment]
@jintopvalue ครบไหมครับ? ยังมีตรงไหนอีกไหมในส่วนของ logo LinePay ที่เปลี่ยน

**Comment by jintopvalue** [comment]
@joomlacorner ไม่มีแล้วค่ะ ครบแล้วค่ะ ขอบคุณค่า
