### ISSUE TITLE
Email Template

### ISSUE THREAD

**Issue by jam-krisada** [topvalue/test_site#31]
1 ) สมัครสมาชิก
2 ) รายการสั่งซื้อถูกสร้าง
3 ) ได้รับรายการชำระเงิน
4 ) จัดส่งสินค้าแล้ว

**Comment by jam-krisada** [comment]
1 ) อีเมลสมัครสมาชิก บน .xyz 
![screen shot 2559-08-03 at 3 30 22 pm](https://cloud.githubusercontent.com/assets/19877215/17359072/3d88fab4-598f-11e6-9080-7d1f223f8514.png)

![screen shot 2559-08-03 at 4 20 55 pm](https://cloud.githubusercontent.com/assets/19877215/17360535/55377f6c-5996-11e6-8517-bdb3f98fc22c.png)

**Comment by jam-krisada** [comment]
2 ) รายการสั่งซื้อถูกสร้าง บน .xyz
![screen shot 2559-08-04 at 10 56 58 am](https://cloud.githubusercontent.com/assets/19877215/17389908/3d04e366-5a32-11e6-863f-3f51208040a7.png)

**Comment by jam-krisada** [comment]
3 ) ได้รับรายการชำระเงิน บน .xyz
![screen shot 2559-08-04 at 10 56 33 am](https://cloud.githubusercontent.com/assets/19877215/17389918/4f13984a-5a32-11e6-9197-dadbbc9c8d35.png)

**Comment by jam-krisada** [comment]
4 ) จัดส่งสินค้าแล้ว
![screen shot 2559-08-04 at 11 11 55 am](https://cloud.githubusercontent.com/assets/19877215/17390121/4a8413a2-5a34-11e6-9e7f-e6f3c2701691.png)

**Comment by jam-krisada** [comment]
@joomlacorner email templete จะเหมือนในเว็บ .com แล้วครับ

**Comment by jintopvalue** [comment]
@jam-krisada 
1. รบกวนแก้เวลาทำการให้หน่อยค่ะ เป็น 08:30-18:30 ค่ะ
![image](https://cloud.githubusercontent.com/assets/20397170/17468614/e7e73364-5d53-11e6-8ac0-9fe80f67ca39.png)

2. อยากให้มีรูปสินค้าในแต่ละรายการด้วยค่ะ 

3. ข้อ 3) กับ 4) ใช้ template เดียวกันกับข้อ 2) ได้ไหมคะ? คือข้อ 2) ข้อมูลชำระเงินและจัดส่งมาก่อนรายการสินค้า แต่ข้อ 3) กับ 4) รายการสินค้าขึ้นก่อนอ่ะค่ะ อยากให้ใช้ template เดียวกันตามไฟล์ที่เคยแชร์ในไดร์ฟน่ะค่ะ 

4. ข้อ 2)  ตรง subtotal กับ Grand total ย้ายคำว่า "บาท" ขึ้นมาอยู่บรรทัดเดียวกันกับราคาให้ทีค่ะ

**Comment by jam-krisada** [comment]
@jintopvalue แก้ไขเวลาใน script ให้แล้วครับ
![screen shot 2559-08-25 at 1 59 20 pm](https://cloud.githubusercontent.com/assets/19877215/17959684/2f36e644-6acc-11e6-8eba-8d3cfbaafa97.png)
2) ปรับย้ายตำแหน่งขึ้นตาม 2) แล้วครับ

**Comment by joomlacorner** [comment]
@jintopvalue  ข้อ 1 ที่อยากให้มีรูปสินค้าในอีเมล ด้วย  แยกเป็น feature ใหม่ ที่มีค่าใช้จ่ายครับ
เพราะว่าต้องเขียน function  หาวิธีในการแสดงภาพในอีเมล์  เนื่องจากใน Magento ไม่มีส่วนนี้ ต้องทำขึ้นมาใหม่
issue #69

**Comment by jam-krisada** [comment]
แก้ปัญหาเรื่อง บาท ตกบรรทัดเรียบร้อยแล้วครับ
![screen shot 2559-09-09 at 4 59 50 pm](https://cloud.githubusercontent.com/assets/19877215/18383341/484ac13e-76af-11e6-9158-abdf1c266c68.png)
![screen shot 2559-09-09 at 5 10 54 pm](https://cloud.githubusercontent.com/assets/19877215/18383563/65a50680-76b0-11e6-9d74-a74d03618c7d.png)
