### ISSUE TITLE
[Help] ไม่สามารถ Gen feed ได้ค่ะ

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#32]
เปลี่ยนค่า filter เพื่อ gen feed ใหม่แต่ขึ้น error ตามนี้ค่ะ
![image](https://cloud.githubusercontent.com/assets/20397170/17397722/93d624b2-5a63-11e6-850a-457d858af17b.png)

**Comment by joomlacorner** [comment]
@jintopvalue อันนี้บน  .com หรือ .xyz ครับ ?   อันไหนที่เป็น bug บน .com  ระบุไว้ให้ด้วยนะครับ  เพราะว่า issue ในนี้จะ focus ไปที่ .xyz ครับ คือสิ่งที่จะมาแทนเว็บ .com ครับ  bug ส่วนมากถูกแก้ไขแล้ว .xyz

**Comment by jintopvalue** [comment]
@joomlacorner ตอนนี้กำลังลองใช้ใน .xyz ค่ะ ลองเจน feed แล้วขึ้นแบบนี้ค่ะ
![image](https://cloud.githubusercontent.com/assets/20397170/17430422/54fcaffc-5b1e-11e6-81bf-054ffbf0e0f7.png)

**Comment by jam-krisada** [comment]
@jintopvalue ลอง gen อีกครั้งครับผม แก้ไข Error getId() แล้วครับผม

**Comment by jam-krisada** [comment]
เทสการ Gen และ แก้ไขปัญหาเรื่อง Encode ที่ทำให้ XML ไฟล์ที่ได้มา Error เรียบร้อยแล้วครับ
