### ISSUE TITLE
[Question] ไซส์ของแบนเนอร์กับความเร็วในการโหลดเว็บค่ะ

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#33]
ตอนนี้แบนเนอร์ใหญ่ที่หน้าเว็บที่ใช้กันอยู่มีแบบความละเอียดสูงกับความละเอียดต่ำค่ะ 
ความละเอียดต่ำมีขนาดประมาณ 80-90kb ส่วนความละเอียดสูงจะอยู่ที่ 400 kb
จะมีประจำอยู่ 5-9 รูป  บางทีก็ใช้ละเอียดสูงต่ำปนกันไป แต่อยากจะใช้แบบเดียวมากกว่า

อยากทราบว่าแบนเนอร์จำนวน 5-9 รูปนี้ถ้าใช้แบบความละเอียดสูงหมดเลย กับ ความละเอียดต่ำหมดเลย 
จะโหลดช้าเร็วต่างกันอย่างเห็นได้ชัดไหมคะ?

![image](https://cloud.githubusercontent.com/assets/20397170/17399936/43651400-5a6f-11e6-9250-5c6cb42d248e.png)

**Comment by joomlacorner** [comment]
มีผลครับ ควร Optimize image ก่อน แล้วก็ไม่ควรมี banner เยอะเกินไปใน ช่วงเวลาเดียวกัน 
เพราะคนที่จะเห็นครบหมดคือคนที่ต้องเปิดหน้าเว็บแช่ไว้น่านๆ เท่านั้น

**Comment by jintopvalue** [comment]
@joomlacorner Optimize image คือยังไงเหรอคะ? ใช่ Save for web หรือเปล่าคะ

**Comment by jam-krisada** [comment]
@jintopvalue ใช้ Save for web หรือ https://kraken.io/ ก็ได้ครับ
