### ISSUE TITLE
[New Feature] เพิ่ม Banner ด้านบนแบบ Amazon 

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#34]
อยากเพิ่มแบนเนอร์ด้านบนขนาด 1210x80 ไว้สำหรับโปรโมทกิจกรรมของเว็บแบบ Amazon ค่ะ
![image](https://cloud.githubusercontent.com/assets/20397170/17424139/37ec1caa-5aeb-11e6-9280-6bfcdd145d19.png) 

แต่อยากให้อยู่ต่อจากแถบสีเทานี้ค่ะ ไม่อยากได้บนสุดเหมือน Amazon 
![image](https://cloud.githubusercontent.com/assets/20397170/17424227/07922e72-5aec-11e6-9347-450a1b706e37.png)

**Comment by jam-krisada** [comment]
ขั้นตอนในการดำเนินการ
1. เพิ่ม layout แทรกระหว่าง Header กับ Top Header
2. แทรก static block ที่สร้างขึ้นมาใหม่
3. อัพโหลดรูปภาพพร้อมใส่ลิงค์

**Comment by jam-krisada** [comment]
ตัวอย่าง

![screen shot 2559-09-02 at 4 28 17 pm](https://cloud.githubusercontent.com/assets/19877215/18199405/4d034e92-712a-11e6-8243-c43aa06477da.png)

![57c7ef0ana3247726](https://cloud.githubusercontent.com/assets/19877215/18199413/5ab4b382-712a-11e6-9b2f-01de42d37194.jpg)

**Comment by oopbest** [comment]
@jam-krisada 
เพิ่มให้แล้วนะครับ

<img width="1206" alt="screen shot 2559-09-12 at 9 57 12 am" src="https://cloud.githubusercontent.com/assets/21325913/18423470/813acbca-78cf-11e6-9d66-11bad2d24af4.png">

**Comment by jam-krisada** [comment]
@oopbest 
ให้ใช้คำสั่ง getChildHtml ใส่ไว้ใน Template /Applications/MAMP/htdocs/website/magento/.modman/theme-wolverine/app/design/frontend/wolverine/default/template/page

![screen shot 2559-09-12 at 5 10 22 pm](https://cloud.githubusercontent.com/assets/19877215/18432394/ec83bb62-790b-11e6-9f89-aeff2ae573fb.png)

ควรใส่ไว้ในทุกๆหน้าโครงสร้างที่ต้องการแสดงผล
![screen shot 2559-09-12 at 5 10 26 pm](https://cloud.githubusercontent.com/assets/19877215/18432408/fba3196c-790b-11e6-9679-1c6792ff80ce.png)

สร้าง Static Block และนำไปใช้งานใน .xml ไฟล์
โดยให้ผู้ใช้งานใส่สี ตามนี้ครับ
![screen shot 2559-09-12 at 5 13 50 pm](https://cloud.githubusercontent.com/assets/19877215/18432468/4ff9aac6-790c-11e6-9e50-78381d4993d7.png)

**Comment by oopbest** [comment]
@jintopvalue @jam-krisada 
แก้ให้แล้วนะครับ
![screen shot 2559-09-13 at 12 23 25 pm](https://cloud.githubusercontent.com/assets/21325913/18462514/26223ba4-79ad-11e6-8f6b-fa22f150216d.png)
