### ISSUE TITLE
ถ้ากด check out โดยที่ยังไม่ได้ login ไม่มี social login ให้เลือกค่ะ

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#35]
ช่วยเพิ่ม social login ให้ด้วยค่ะ
![image](https://cloud.githubusercontent.com/assets/20397170/17468070/8b4fd9bc-5d4e-11e6-9fd2-d9bdcbaa088e.png)

**Comment by jam-krisada** [comment]
@jintopvalue ปรับแก้ไขให้แล้วครับ
![screen shot 2559-08-16 at 11 26 46 am](https://cloud.githubusercontent.com/assets/19877215/17687954/4f7e74be-63a4-11e6-96b6-33d1bd3f5908.png)

cc: @joomlacorner
