### ISSUE TITLE
ในหน้า cart Handling&shipping ยาวกินพื้นที่ราคาค่ะ

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#36]
http://www.topvalue.xyz/checkout/cart/ 
Handling&shipping ยาวกินพื้นที่ราคาค่ะ

![image](https://cloud.githubusercontent.com/assets/20397170/17468223/000f46ba-5d50-11e6-84ad-4a89e5c63653.png)

**Comment by jam-krisada** [comment]
@jintopvalue ปรับให้สั่นลงแล้วครับ
![screen shot 2559-08-16 at 12 25 49 pm](https://cloud.githubusercontent.com/assets/19877215/17688774/92f521ae-63ac-11e6-99c7-c6fb25f6c3d9.png)

**Comment by jam-krisada** [comment]
cc: @joomlacorner
