### ISSUE TITLE
ปรับ field ใน Shipping information ค่ะ

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#37]
อยากปรับให้ใช้ง่ายสำหรับคนไทยกว่านี้น่ะค่ะ แล้วก็อยากมี option ให้ลูกค้าสามารถ
แก้ zip/postal code เองได้ บางทีในเขตเดียวกันแต่คนละตำบล รหัสไปรษณีย์ก็ต่างกันค่ะ
แล้วลูกค้าก็จะมีปัญหาตอนเช็คเอ๊าท์ว่าหารหัสไปรษณีย์ไม่เจอ 

หลังจากเลือกจังหวัดกับเขตที่เป็น dropdown แล้ว อยากให้ขึ้นรหัสไปรษณีย์ที่น่าจะใช่ 
แต่ถ้าลูกค้าอยากจะกดแก้ไข ก็สามารถพิมพ์ได้

![image](https://cloud.githubusercontent.com/assets/20397170/17471299/5c3a0b2e-5d6d-11e6-85a3-14af73d5066d.png)

**Comment by jam-krisada** [comment]
@jintopvalue เพื่อป้องกันความผิดพลาดที่เกิดจากผู้ใช้งานให้เหลือความผิดพลาดน้อยที่สุด
ผมว่าจำเป็นต้องบังคับให้เลือกเฉพาะที่มีครับ อาจจะปรับย้าย fileds ให้อยู่ในตำแหน่งที่เหมาะสมก็จะแก้ปัญหาความสับสนของผู้ใช้งานได้

![screen shot 2559-08-09 at 1 44 27 pm](https://cloud.githubusercontent.com/assets/19877215/17507069/b4d1eab6-5e37-11e6-8ab9-a70850274031.png)

cc : @joomlacorner

**Comment by jintopvalue** [comment]
@jam-krisada ได้ค่ะ ปรับย้าย field ให้จังหวัดกับเขตแยกออกมาก็ได้ค่ะ น่าจะเข้าใจง่ายขึ้นค่ะ

**Comment by jam-krisada** [comment]
@jintopvalue ปรับแก้ไข Fields แสดงข้อมูลเพิ่มเติมเข้ามาแล้วครับ
![screen shot 2559-08-18 at 5 43 22 pm](https://cloud.githubusercontent.com/assets/19877215/17771082/82ff6df2-656b-11e6-94d8-8b423113c21e.png)

cc : @joomlacorner

**Comment by jintopvalue** [comment]
@jam-krisada อยากจะให้คนอื่นในทีมจินช่วยทดสอบดูด้วยค่ะ แต่ตอนนี้ที่ .xyz ไม่มีสินค้าให้เลือกเลย ช่วยเปิดให้เทสต์ทีได้ไหมคะ

**Comment by jam-krisada** [comment]
เหลือในหน้า address information ที่ยังไม่ได้ทำ
![screen shot 2559-08-31 at 3 00 26 pm](https://cloud.githubusercontent.com/assets/19877215/18120802/af4b7822-6f8b-11e6-9dde-f5bec9fa7e95.png)

**Comment by jam-krisada** [comment]
@oopbest ขั้นตอนการเพิ่ม Filed Zipcode ใน หน้า New Address 
- เขียน แก้ไขไฟล์ riot tag 
theme-wolverine/skin/frontend/wolverine/default/js/tags/zipcode.tag
- หรือ เขียนไฟล์​ riot ขึ้นมาใหม่เพื่อใช้สำหรับหน้านี้ครับ
- ไฟล์ Template จะอยู่ที่นี้ครับ 
/theme-wolverine/app/design/frontend/wolverine/default/template/customer/address/edit.phtml

**Comment by jam-krisada** [comment]
@oopbest ตรวจสอบแล้วครับ
![screen shot 2559-09-06 at 11 59 57 am](https://cloud.githubusercontent.com/assets/19877215/18262195/8a4aa442-7429-11e6-9638-684a9417e946.png)
