### ISSUE TITLE
แก้ไข display ของ bestseller และ flashsale ค่ะ

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#38]
ขอปรับนิดนึงค่ะ แค่เอาขีดคั่นกลางและ view details ออกค่ะ 
![image](https://cloud.githubusercontent.com/assets/20397170/17540548/3d30ba8c-5ee1-11e6-9bff-dd2257117075.png)

**Comment by jam-krisada** [comment]
@jintopvalue ปรับแก้ไขให้แล้วครับ
<img width="1219" alt="screen shot 2559-08-16 at 12 18 08 am" src="https://cloud.githubusercontent.com/assets/19877215/17672508/e79d462a-6346-11e6-95b6-83442a2cad58.png">
