### ISSUE TITLE
Error ใน Wishlist ค่ะ 

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#39]
1) เข้าไปดูที่ My wishlist แล้วเจอ error นี้ค่ะ 
![image](https://cloud.githubusercontent.com/assets/20397170/17547944/b9d5f8ae-5f13-11e6-8a9d-8d07e0d45229.png)

2) ที่หน้า gallery กดหัวใจเพื่อเพิ่มเข้า wishlist หรือเอาออกจาก wishlist แล้วหัวใจหมุนไม่หยุดค่ะ หรือกด edit จาก my wishlist ก็หัวใจก็หมุนไม่หยุดค่ะ กดซ้ำเพื่อเอาออกจาก wishlist ไม่ได้ด้วยค่ะ
![image](https://cloud.githubusercontent.com/assets/20397170/17550504/76e29df2-5f1f-11e6-8bd3-5fb84d6ab9f7.png)

**Comment by jam-krisada** [comment]
@jintopvalue 
1) แก้ไข error ใน wishlist แล้วครับ
![screen shot 2559-08-16 at 10 36 29 am](https://cloud.githubusercontent.com/assets/19877215/17687191/4aa0d70e-639d-11e6-8612-861041f1c5c1.png)

**Comment by jam-krisada** [comment]
@jintopvalue 2) ดำเนินการแก้ไข script แล้วครับ
![screen shot 2559-08-16 at 10 50 21 am](https://cloud.githubusercontent.com/assets/19877215/17687446/44e318f2-639f-11e6-8165-24e3089e720a.png)

@joomlacorner แก้ไขแล้วครับผม
