### ISSUE TITLE
กดดำเนินการชำระเงินแล้วเด้งกลับหน้าเดิม ไม่ไปต่อ

### ISSUE THREAD

**Issue by joomlacorner** [topvalue/test_site#4]
กด "ชำระเงิน" จากหน้า Cart (http://www.topvalue.com/checkout/cart/) ไม่ไปหน้า Check-out รีเฟรชแล้วอยู่หน้า Cart เหมือนเดิม

1 เข้า www.topvalue.com ( .xyz )

2 Log in Log in 

3 เลือกสินค้า#1 ใส่รถเข็น สินค้าเข้ารถเข็น 

4 กด "ดำเนินการชำระเงิน" จากหน้า Cart (http://www.topvalue.com/checkout/cart/) ไปหน้า checkout (https://www.topvalue.com/checkout/onepage/) ไปหน้า checkout

**Comment by wanidagithub** [comment]
จากการทดสอบ #1 สามารถคลิก"ดำเนินการชำระเงิน" จากหน้า Cart (http://www.topvalue.xyz/checkout/cart/) ไปหน้า Checkout (http://www.topvalue.xyz/checkout/onepage/) สำเร็จ

**Comment by joomlacorner** [comment]
fixed #4
