### ISSUE TITLE
การแสดงราคาในหน้า Product

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#40]
สินค้าบางตัว ราคาขายอยู่ข้างหลังราคาปกติค่ะ 
http://www.topvalue.xyz/k09028000123501.html
![image](https://cloud.githubusercontent.com/assets/20397170/17550380/e09268a0-5f1e-11e6-8f90-69cc22daba4b.png)

http://www.topvalue.xyz/1110269355533-i-mobile-hitz-21.html
![image](https://cloud.githubusercontent.com/assets/20397170/17551184/c698ad02-5f22-11e6-967d-806a557c725f.png)

อยากให้อยู่ข้างหลังหมดค่ะ และบอกว่า save กี่ % เหมือนกันค่ะ
![image](https://cloud.githubusercontent.com/assets/20397170/17550400/fde832ea-5f1e-11e6-9f13-26c6ca29d5de.png)

**Comment by jam-krisada** [comment]
@jintopvalue @joomlacorner ดำเนินการแก้ไขแล้วครับ
<img width="949" alt="screen shot 2559-08-15 at 10 55 48 pm" src="https://cloud.githubusercontent.com/assets/19877215/17670284/71ff2d9e-633b-11e6-9896-4efb05390f2e.png">
<img width="986" alt="screen shot 2559-08-15 at 10 55 59 pm" src="https://cloud.githubusercontent.com/assets/19877215/17670290/7ce37f94-633b-11e6-826f-f500bfb9e653.png">
