### ISSUE TITLE
หน้าหมวดหมู่

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#41]
1) หมวดโทรศัพท์มือถือ กับ โทรศัพท์/แท็บเล็ต เข้าไม่ได้ค่ะ
http://www.topvalue.xyz/mobiles/-10.html
http://www.topvalue.xyz/mobiles.html
![image](https://cloud.githubusercontent.com/assets/20397170/17550721/8b586478-5f20-11e6-9dc5-930c065bc0a3.png)
![image](https://cloud.githubusercontent.com/assets/20397170/17550728/91d4ed76-5f20-11e6-8515-98f1767b3fd9.png)

2) expand หมวดทั้งหมดแล้วดูลำบากอ่ะค่ะ ทำเป็นชั้นๆซ่อนไว้คล้ายๆแบบนี้ได้ไหมคะ
พอกดให้ show ค่อย expand หมวดย่อยต่อค่ะ
![image](https://cloud.githubusercontent.com/assets/20397170/17551014/0808d984-5f22-11e6-8719-0e1ab58fde0c.png)

![image](https://cloud.githubusercontent.com/assets/20397170/17550904/832d5ece-5f21-11e6-83a1-7c3f410d2866.png)

3) รายชื่อ brand เยอะและหายากค่ะ ช่วยเพิ่มช่อง search คล้ายๆแบบนี้ให้หน่อยค่ะ
![image](https://cloud.githubusercontent.com/assets/20397170/17550994/f13c1b1c-5f21-11e6-86f8-62e3bd4d97f1.png)

**Comment by jam-krisada** [comment]
@jintopvalue 
1) เดี๋ยวผมพยายามทำให้เกิดปัญหานี้ให้ได้อีกครั้งนะครับ เบื้องต้นผมทดสอบเข้ายังไม่พบครับ
<img width="1218" alt="screen shot 2559-08-15 at 10 44 10 pm" src="https://cloud.githubusercontent.com/assets/19877215/17669982/17d0cb58-633a-11e6-9d8c-587951441cd0.png">
<img width="1212" alt="screen shot 2559-08-15 at 10 44 26 pm" src="https://cloud.githubusercontent.com/assets/19877215/17669986/20709a40-633a-11e6-90fd-0673b950d421.png">

2) เดี๋ยวผมลองหาวิธีทางแก้ไขที่น่าจะโอเคให้นะครับ เนื่องจาก ช่องด้านซ้ายขนาดเล็กมากครับ หากทำเป็น ชั้นๆก็จะพบปัญหาชื่อตกบรรทัดอยู่ครับ
เนื่องจากข้อ 3) ยังไม่เคยมีอยู่อาจจะต้องประเมินเวลาและค่าใช้จ่ายให้ครับ

**Comment by jintopvalue** [comment]
@jam-krisada ข้อ 3) ไว้ก่อนก็ได้ค่ะ ส่วนข้อ 2) ถ้าหาวิธีแก้ไม่ได้ก็ใช้แบบนี้ก่อนได้ค่ะ
