### ISSUE TITLE
สินค้าหมวดโทรศัพท์มือถือไปอยู่ในหมวดคอมพิวเตอร์ค่ะ

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#42]
สินค้าของหมวดโทรศัพท์มือถือ/แท็บเล็ต ไปอยู่ในหมวด คอมพิวเตอร์/IT/กล้อง ด้วยค่ะ ย้ายให้เหลือแค่ โทรศัพท์มือถือ/แท็บเล็ต ได้ไหมคะ เห็นที่หลังบ้านติ๊กไว้สองหมวดหลักอ่ะค่ะ
http://www.topvalue.xyz/gear4-iphone-6-ultra-thin-ice.html
![image](https://cloud.githubusercontent.com/assets/20397170/17551193/dd264da4-5f22-11e6-93bf-81e83693d357.png)

http://www.topvalue.xyz/1120365927404-apple-iphone-6-16gb-mac-gray-silver-gold.html
![image](https://cloud.githubusercontent.com/assets/20397170/17551202/e9d3425a-5f22-11e6-8e97-c8dac03f62b2.png)

**Comment by jam-krisada** [comment]
@jintopvalue เนื่องจาก การสร้าง Beadcrumb จะเอาหมวดหลักและหมวดย่อยที่เป็นไปได้ มาแสดงเพื่อให้ลูกค้าเลือกหมวดที่ต้องการเข้าไปได้มากที่สุด จึงมีหมวดต่างๆที่ถูกเลือกอยู่มาแสดงครับ

http://www.topvalue.xyz/gear4-iphone-6-ultra-thin-ice.html
<img width="600" alt="screen shot 2559-08-15 at 10 33 24 pm" src="https://cloud.githubusercontent.com/assets/19877215/17669662/ac001042-6338-11e6-9fee-b464eb00e8da.png">

http://www.topvalue.xyz/1120365927404-apple-iphone-6-16gb-mac-gray-silver-gold.html
<img width="259" alt="screen shot 2559-08-15 at 10 36 50 pm" src="https://cloud.githubusercontent.com/assets/19877215/17669709/e41f1036-6338-11e6-83b1-fb5695de7949.png">

**Comment by jintopvalue** [comment]
@jam-krisada  สามารถแก้ให้อยู่หมวดเดียวได้ไหมคะ เพราะว่าเวลาตั้ง filter ทำ coupon code 
น่าจะเป็นปัญหาค่ะถ้าอยู่สองหมวดค่ะ และเวลาcreate product จาก ns ก็จะมีแค่ class เดียวด้วยค่ะ

**Comment by jam-krisada** [comment]
@jintopvalue เรื่องหมวดหมู่ผม import มาจากระบบเดิมครับ ไม่แน่ใจใครเลือกไว้ ปกติ magento เลือกได้มากกว่า 1 หมวดอยู่แล้วครับ ยังไงให้เค้าติ๊กออกนะครับ ตอนขึ้นใช้งานจริง

cc: @joomlacorner

**Comment by jintopvalue** [comment]
@jam-krisada ค่ะ ขอบคุณมากค่ะ
