### ISSUE TITLE
เมนูหมวด"สุขภาพและความงาม" เกินขอบค่ะ

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#43]
หมวดนี้ข้างล่างเกินมาอ่ะค่ะ ตัดบางส่วนของชื่อหมวดออกก็ได้ค่ะ จะได้ขึ้นไปอยู่ในกรอบเดียวกันกับหมวดอื่นๆค่ะ 
![image](https://cloud.githubusercontent.com/assets/20397170/17551296/706b7238-5f23-11e6-98d5-1bf95cbb0808.png)

**Comment by jam-krisada** [comment]
@jintopvalue ผมแก้ไขพร้อมกับ #44 หลังจาก Final คำที่จะแสดงนะครับ

**Comment by jintopvalue** [comment]
@jam-krisada จินกำลังกำหนด Text และ landing page ที่จะอยู่ใน megamenu อ่ะค่ะ
ในส่วนของ landing page ให้ใส่เป็นหมวดๆแบบนี้หรือว่าเป็น ID คะ
![image](https://cloud.githubusercontent.com/assets/20397170/17961511/64a03056-6ad6-11e6-8a11-0dbc3243a797.png)

**Comment by jam-krisada** [comment]
ให้กรอกเป็น category url ที่ @jintopvalue เคยส่งตารางให้ผมครับ

**Comment by jintopvalue** [comment]
@jam-krisada ขอโทษด้วยค่ะ ใน catalog URL จินลืมใส่บางช่อง (สีเหลือง) ยังเพิ่มทันไหมคะ T_T

https://docs.google.com/a/marvelic.co.th/spreadsheets/d/1yztssqPZIoX_G3JmMetU9x5bPjOzH4LIWH0deaKuj-k/edit?usp=sharing 
![image](https://cloud.githubusercontent.com/assets/20397170/17963876/bb33b478-6ae1-11e6-9812-8d41a804a22c.png)

**Comment by jam-krisada** [comment]
ยังเพิ่มทันครับผม รบกวน @jintopvalue ใส่เฉพาะ url สุดท้ายเท่านั้นครับ url หมวด parent ไม่ต้องกรอกครับ

**Comment by jintopvalue** [comment]
@jam-krisada หมายถึง ข้อความหลัง "/" สุดท้ายหรอคะ

**Comment by jam-krisada** [comment]
@jintopvalue 
เช่น "อุปกร์เบ็ดเตล็ดในครัว" จะกรอก url เป็น "kitchen-tools"

**Comment by jintopvalue** [comment]
@jam-krisada แบบนี้เหรอคะ
![image](https://cloud.githubusercontent.com/assets/20397170/18003066/a9f8771e-6bb5-11e6-8cad-cb49b0c481fa.png)

**Comment by jam-krisada** [comment]
@jintopvalue ครับผม จะต้องไม่ซ้ำกับหมวดอื่นๆนะครับ
![screen shot 2559-08-26 at 5 52 36 pm](https://cloud.githubusercontent.com/assets/19877215/18003101/e7edaeea-6bb5-11e6-97df-8442f464f0bb.png)

**Comment by jintopvalue** [comment]
@jam-krisada บางหมวดก็มี URL นี้อยู่แล้วอ่ะค่ะ

**Comment by jam-krisada** [comment]
คุณจินแยกเป็น 2 ไฟล์นะครับ
1. Category URL ซ้ำกันได้ถ้า ชื่อด้านหน้าเหมือนกันครับ แต่ถ้าคนละหมวดหมู่ url จะต้องไม่ซ้ำกันนะครับ
ประมาณนี้ครับ
เสื้อผ้าผู้ชาย/อื่นๆ man-other
เสื้อผ้าผู้หญิง/อื่นๆ women-other
2. URL สำหรับ Mega Menu หน้าบ้าน

**Comment by jam-krisada** [comment]
@jintopvalue ดูจากเว็บเดิมน่าจะช่วยได้ครับ

**Comment by jintopvalue** [comment]
@jam-krisada 
1) ตามไฟล์ Catalog URL เดิมค่ะ จิน edit แล้วค่ะ https://docs.google.com/a/marvelic.co.th/spreadsheets/d/1yztssqPZIoX_G3JmMetU9x5bPjOzH4LIWH0deaKuj-k/edit?usp=sharing

2) File สำหรับคำที่จะ display และ landing page ของเมนูใน Megamenu ค่ะ
[MEGAMENU.xlsx](https://github.com/topvalue/test_site/files/440693/MEGAMENU.xlsx)




3) รูปแบนเนอร์และ landing page ที่อยู่ใน Megamenu ค่ะ 
1. appliances > appliances/consumers-electronics/tv
2. beauty > health-beauty/makeups/lips-makeups
3. computer-it-camera > computers-it-cameras/laptops-computers/laptops
4. mobile > mobile-tablets/mobile
5. momnbaby > mom-baby/diapers-cleaning-products/diapers
6. pet > pets/dogs/dogs-foods/dogs-treats
[Megamenu Banner.zip](https://github.com/topvalue/test_site/files/440692/Megamenu.Banner.zip)

**Comment by jam-krisada** [comment]
@jintopvalue 
จากไฟล์​https://docs.google.com/a/marvelic.co.th/spreadsheets/d/1yztssqPZIoX_G3JmMetU9x5bPjOzH4LIWH0deaKuj-k/edit?usp=sharing ยังเป็นโครงสร้าง mapping เดิมก่อนอันล่าสุดอยู่นะครับ

ตอนนี้ผม export category จาก .xyz มาเพื่อเติม url เดี๋ยวผมทำให้ครบแล้วส่งให้ @jintopvalue เช็คอีกครั้งนะครับ

เปรียบเทียบการ map ล่าสุดครับ
![screen shot 2559-08-29 at 11 21 55 am](https://cloud.githubusercontent.com/assets/19877215/18040749/834ed202-6ddb-11e6-949a-43208a2cc7de.png)

ไฟล์​ category url ยังไม่อัพเดทล่าสุด
![screen shot 2559-08-29 at 11 24 33 am](https://cloud.githubusercontent.com/assets/19877215/18040754/93431c90-6ddb-11e6-8aa6-539c1acbc9be.png)

กำลังทำ mapping url ให้ครับ
![screen shot 2559-08-29 at 11 28 11 am](https://cloud.githubusercontent.com/assets/19877215/18040764/b788aa20-6ddb-11e6-82f3-f8ffce86a5f8.png)

cc: @joomlacorner

**Comment by jam-krisada** [comment]
@jintopvalue รบกวนช่วยเติม URL ที่ขาดให้หน่อยครับ ผมพยายาม map จากที่มีได้ประมาณนี้ครับ
[category.xlsx](https://github.com/topvalue/test_site/files/441695/category.xlsx)

**Comment by jam-krisada** [comment]
@jintopvalue ผมมึนไฟล์ครับ สรุปเดี๋ยวเราใช้ category final ที่ ไฟล์ 
[Category_19-8-4.xlsx](https://github.com/topvalue/test_site/files/441779/Category_19-8-4.xlsx)
ใช่ไหมครับ เดี๋ยวผมต้อง map และ export ใหม่ 
ส่วนไฟล์ category url รอผมตั้งต้นให้อีกไฟล์นะครับ

@joomlacorner

**Comment by jintopvalue** [comment]
@jam-krisada แก้ไขแล้วค่ะ
[category_29-8-16.xlsx](https://github.com/topvalue/test_site/files/441908/category_29-8-16.xlsx) 
สีเหลืองคือมีการเพิ่ม/edit ชื่อเฉยๆค่ะ ส่วนสีแดงคือมีการเรียงลำดับใหม่ มีผลต่อ path ค่ะ 
![image](https://cloud.githubusercontent.com/assets/20397170/18044314/73b39f5a-6df7-11e6-912c-5edb90356870.png)

**Comment by jam-krisada** [comment]
Final Mapping Category URL
[category_mapping.xlsx](https://github.com/topvalue/test_site/files/453955/category_mapping.xlsx)
