### ISSUE TITLE
หมวดสุขภาพและความงามในหลังบ้านไม่ตรงกับหน้าเว็บค่ะ

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#44]
ต้องเป็น "ผลิตภัณฑ์ดูแลตัวเอง" เหมือนหน้าเว็บค่ะ ไม่ใช่ "ดูแลเส้นผม"
![image](https://cloud.githubusercontent.com/assets/20397170/17551907/e9de4048-5f26-11e6-9c68-70b24160d76e.png)

![image](https://cloud.githubusercontent.com/assets/20397170/17551927/04eb2b1c-5f27-11e6-80d0-978521d8f01e.png)

**Comment by jam-krisada** [comment]
รบกวน @jintopvalue แนบไฟล์ Final หัวข้อย่อยทุกหมวดไว้ในนี้เดี๋ยวผมปรับแก้ไขทีเดียวครับ

**Comment by jintopvalue** [comment]
@jam-krisada ไฟล์ Final ค่ะ
[Category_16-8-4.xlsx](https://github.com/topvalue/test_site/files/419696/Category_16-8-4.xlsx)

**Comment by jam-krisada** [comment]
@jintopvalue คุณจินผมรบกวนขอ url ของแต่ละหมวดหมู่ด้วยครับ

**Comment by jintopvalue** [comment]
@jam-krisada 
[Catalog URL(19-8-16).xlsx](https://github.com/topvalue/test_site/files/426224/Catalog.URL.19-8-16.xlsx) จินเพิ่มไปในไฟล์บน drive ด้วยค่ะ https://docs.google.com/a/marvelic.co.th/spreadsheets/d/1yztssqPZIoX_G3JmMetU9x5bPjOzH4LIWH0deaKuj-k/edit?usp=sharing 


ส่วน Category มี Edit คำสะกดผิดในหมวดสุขภาพและความงาม 2 จุดค่ะ
อันนี้คือไฟล์ที่อัพเดทแล้วค่ะ [Uploading Category_19-8-4.xlsx…]()

**Comment by jam-krisada** [comment]
@jintopvalue รบกวนแชร์ให้ jam.krisada@gmail.com ทีครับ

**Comment by jintopvalue** [comment]
@jam-krisada แชร์แล้วค่ะ

**Comment by jam-krisada** [comment]
@jintopvalue ขอบคุณครับ

**Comment by jam-krisada** [comment]
@jintopvalue อันนี้คือ Final แล้วใช่ไหมครับผม
ไฟล์ Category URL วันที่ 19_08_59
[19_08_59.xlsx](https://github.com/topvalue/test_site/files/426267/19_08_59.xlsx)

**Comment by jintopvalue** [comment]
@jam-krisada ใช่ค่ะ

**Comment by jam-krisada** [comment]
mapping final เรียบร้อยครับ
