### ISSUE TITLE
ปัญหาของ Daily Deal pro

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#45]
1)  สินค้าที่อยู่ในช่วง daily deal ราคาในช่องเสิร์ชไม่ใช่ราคาที่ลดอยู่ค่ะ อยากให้โชว์ราคา deal อ่ะค่ะ
![image](https://cloud.githubusercontent.com/assets/20397170/17765440/17a39396-6550-11e6-8c11-b277d9bb78e8.png)
![image](https://cloud.githubusercontent.com/assets/20397170/17765424/f15d4b1e-654f-11e6-8b8e-b3d413fdd260.png)

2) Feed ที่ gen ออกมาก็ไม่ใช่ราคา deal ค่ะ สามารถเจนออกมาเป็นราคา deal ได้ไหมคะ
3) ตอนปรับแก้เวลาอ่ะค่ะ ถ้า interface locale เป็น ไทย ทั้งที่เลือกวันเดือนปีเป็น วันนี้ พอกด save แล้ว
จะย้อนกลับไปปี 1970 ตลอดเลยเลยค่ะ
![image](https://cloud.githubusercontent.com/assets/20397170/17765643/4dc0e63a-6551-11e6-9028-4c3e1b8f799a.png)

**Comment by jam-krisada** [comment]
@jintopvalue 
1) เดี๋ยวผมยิงราคา Flash Sale เข้าไปในระบบ Search ให้ครับ
2) ถ้าต้องการให้เป็นราคา deal ต้องแก้ไข Extension นี้เพื่อดึงราคาลดมา เนื่องจากเป็นคนละ Extension กันทำให้ระบบไม่ได้รองรับในส่วนนี้ไว้ครับ (มีค่าใช้จ่ายเพิ่มเติม)
3 ) ต้องแก้ไข Extension ครับ เนื่องจากเค้าไม่ได้ทำรองรับภาษาอื่นมา (มีค่าใช้จ่ายเพิ่มเติม)

cc : @joomlacorner

**Comment by joomlacorner** [comment]
@jintopvalue  3) ตอนปรับแก้เวลาอ่ะค่ะ ถ้า interface locale เป็น ไทย ทั้งที่เลือกวันเดือนปีเป็น วันนี้ พอกด save แล้ว จะย้อนกลับไปปี 1970 ตลอดเลยเลยค่ะ   

เรื่องวันที่ทั้งระบบน่าจะเป็น ค.ศ นะครับ ไม่ใช่ ปี พ.ศ เวลาใส่ข้อมูล

**Comment by jintopvalue** [comment]
@joomlacorner ตอนใส่ก็ใส่ว่าปี 2016 นะคะ พอกด save เด้งกลับมาเป็น 1970 ค่ะ ถ้าแก้ไม่ได้ไม่เป็นไรค่ะ เดี๋ยวให้ทีมเปลี่ยน interface locale ทุกครั้งก่อนตั้งเวลาค่ะ

**Comment by jam-krisada** [comment]
จะทำระบบ Import Flash Sales ไว้ให้นะครับ จะไม่ต้องกรอกข้อมูลผ่านระบบหลังบ้านครับ 
เพื่อให้ข้อมูลเวลาถูกต้องครับ

**Comment by jam-krisada** [comment]
ย้ายไปรวมกับ #10
