### ISSUE TITLE
issue ที่อาจะเกิดกับ elastic search ค่ะ 

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#48]
ในตัว topvalue.com จู่ๆ elasticsearch ก็ไม่ทำงานค่ะ ใส่ keyword อะไรก็ขึ้นว่า "ไม่พบ" ค่ะ
พี่ต่อ clear index ให้แล้ว หายแล้วค่ะ ส่วนสาเหตุคาดว่าอาจจะเกิดจากที่มีลูกค้าใส่ข้อความยาวขนาดนี้ลงในช่องเสิร์ชค่ะ 
มีวิธีป้องกันยังไงไหมคะ  

![image](https://cloud.githubusercontent.com/assets/20397170/17879824/1e6bf5e2-691f-11e6-943d-7eb48195001f.png)
![image](https://cloud.githubusercontent.com/assets/20397170/17879833/2c35768a-691f-11e6-819c-802f078f349a.png)

**Comment by jam-krisada** [comment]
@jintopvalue ระบบใหม่นี้จะจำกัดความยาวในการค้นหาทำให้ไม่เกิดกรณีนี้ครับ
