### ISSUE TITLE
[Help] Upload รหัสคูปองที่เจนแล้วเข้า magento ใหม่

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#5]
ถ้ามีลิสต์ excel เก็บไว้ว่ารหัสที่ต้องการใช้ต่อมีอะไรบ้าง จะอัพโหลดเข้าไปที่ magento ในเว็บใหม่ได้เลยไหมคะ
ไม่ต้องการข้อมูลเรื่องเงื่อนไขและ status ว่าใช้หรือยัง อัพโหลดแค่รหัสคูปอง เดี๋ยวที่เหลือไปตั้งค่าใหม่ค่ะ

**Comment by joomlacorner** [comment]
ลองเบื้องต้นแล้ว ไม่ง่าย  น่าจะต้องใช้เวลาในการลองอย่างน้อย 3-4 ชั่วโมง  เดี๋ยวจุดหลักๆ ok แล้วจะแทรกให้ครับ

**Comment by jam-krisada** [comment]
ดำเนินการ maually
