### ISSUE TITLE
Check out ไม่ได้ค่ะ

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#50]
จินจะเข้าไปลองดู field ใน shipping information น่ะค่ะ แต่ไปต่อไม่ได้ 
![image](https://cloud.githubusercontent.com/assets/20397170/18039917/90f69606-6dd1-11e6-8666-c5975d82ca58.png)

**Comment by jam-krisada** [comment]
@jintopvalue ลองอีกครั้งครับ ผมแก้ไขให้แล้วครับ

**Comment by jintopvalue** [comment]
@jam-krisada จินลองดูแล้ว ขอปรับหน่อยนะคะ 
ขอปรับการเรียงทั้งใน Billing information และ Shipping information ใช้ลำดับเดียวกันตามนี้นะคะ
อยากให้เรียงลำดับตามนี้น่ะค่ะ
1) เปลี่ยน"ช่องช่วยค้นหา" เป็น "รหัสไปรษณีย์" ค่ะ เพราะ display แต่รหัสไปรษณีย์อยู่แล้วค่ะ
2) ให้อยู่ใกล้ "เขต" กับ "จังหวัด" เพราะว่าเวลากดแล้วมันเปลี่ยนค่าให้อัตโนมัติ จะได้เห็นชัดๆค่ะว่าเปลี่ยน
3) เปลี่ยนเป็นภาษาไทยค่ะ 

![image](https://cloud.githubusercontent.com/assets/20397170/18050411/a9e43b4a-6e18-11e6-8dc0-d40168274b18.png)

**Comment by jam-krisada** [comment]
@jintopvalue ขออนุญาติปิด issue #50 ส่วนการจัดเรียงย้ายไปที่ #62 ครับ
