### ISSUE TITLE
Function ลดสูงสุด x% แต่ไม่เกิน Y บาท เปิดใช้แล้วมี error

### ISSUE THREAD

**Issue by jam-krisada** [topvalue/test_site#56]
Function ลดสูงสุด x% แต่ไม่เกิน Y บาท เปิดใช้แล้วมี error คือ จำนวนเงินที่ลดไม่ตรงกับที่กำหนดค่ะ
![screen shot 2559-07-05 at 4 31 59 pm](https://cloud.githubusercontent.com/assets/144291/16582720/e8ed231a-42da-11e6-8deb-568f2c6c24f9.png)

**Comment by oopbest** [comment]
@jam-krisada  ผมทดสอบแล้ว ไม่มี error นะครับใช้ได้ปกติครับ

<img width="1280" alt="screen shot 2559-09-06 at 1 47 27 pm" src="https://cloud.githubusercontent.com/assets/21325913/18264107/7b72d35e-7438-11e6-8231-158188acff84.png">

<img width="1219" alt="screen shot 2559-09-06 at 1 48 20 pm" src="https://cloud.githubusercontent.com/assets/21325913/18264125/a49bfe40-7438-11e6-9175-ee5b3acc7638.png">
