### ISSUE TITLE
Theming Responsive Login 

### ISSUE THREAD

**Issue by jam-krisada** [topvalue/test_site#63]

**Comment by jam-krisada** [comment]
<img width="374" alt="screen shot 2559-09-09 at 2 00 37 am" src="https://cloud.githubusercontent.com/assets/19877215/18362752/3fe98274-7631-11e6-8335-25a5c6c92690.png">

<img width="374" alt="screen shot 2559-09-09 at 1 59 56 am" src="https://cloud.githubusercontent.com/assets/19877215/18362721/235d5450-7631-11e6-9f65-16e92c6a8bb2.png">
<img width="376" alt="screen shot 2559-09-09 at 1 59 45 am" src="https://cloud.githubusercontent.com/assets/19877215/18362722/235d6fbc-7631-11e6-907d-ff52eda942f6.png">
<img width="375" alt="screen shot 2559-09-09 at 1 59 36 am" src="https://cloud.githubusercontent.com/assets/19877215/18362720/235c3d9a-7631-11e6-8671-10cba0451538.png">
<img width="373" alt="screen shot 2559-09-09 at 2 05 39 am" src="https://cloud.githubusercontent.com/assets/19877215/18362891/f14532fc-7631-11e6-84a3-59bdd727fa30.png">

**Comment by jam-krisada** [comment]
<img width="372" alt="screen shot 2559-09-09 at 3 26 11 am" src="https://cloud.githubusercontent.com/assets/19877215/18366375/a5f0c9d8-7640-11e6-994c-d8b0643528f0.png">
<img width="364" alt="screen shot 2559-09-09 at 3 27 48 am" src="https://cloud.githubusercontent.com/assets/19877215/18366408/c0200058-7640-11e6-82a3-b7478ba474c2.png">
<img width="371" alt="screen shot 2559-09-09 at 3 50 42 am" src="https://cloud.githubusercontent.com/assets/19877215/18366422/cdf5dc70-7640-11e6-96db-3fb0e8efb1f2.png">

**Comment by jam-krisada** [comment]
<img width="371" alt="screen shot 2559-09-09 at 4 17 44 am" src="https://cloud.githubusercontent.com/assets/19877215/18367258/68f7f282-7644-11e6-9773-4ee74ba278fb.png">

<img width="372" alt="screen shot 2559-09-09 at 4 07 29 am" src="https://cloud.githubusercontent.com/assets/19877215/18366968/fb8c4d66-7642-11e6-8540-7ffd0a602160.png">

<img width="372" alt="screen shot 2559-09-09 at 4 08 51 am" src="https://cloud.githubusercontent.com/assets/19877215/18367194/1473ce66-7644-11e6-87a4-ab428fb61e0d.png">

<img width="376" alt="screen shot 2559-09-09 at 4 21 10 am" src="https://cloud.githubusercontent.com/assets/19877215/18367352/eeff6496-7644-11e6-95b9-2a86327d1e0e.png">

<img width="358" alt="screen shot 2559-09-09 at 4 09 00 am" src="https://cloud.githubusercontent.com/assets/19877215/18367193/147349f0-7644-11e6-8258-c5eb00910fea.png">

**Comment by jam-krisada** [comment]
<img width="372" alt="screen shot 2559-09-09 at 4 34 07 am" src="https://cloud.githubusercontent.com/assets/19877215/18367716/b2695832-7646-11e6-9617-931341666f3c.png">
![Uploading Screen Shot 2559-09-09 at 4.34.15 AM.png…]()

**Comment by jam-krisada** [comment]
<img width="370" alt="screen shot 2559-09-09 at 10 38 16 am" src="https://cloud.githubusercontent.com/assets/19877215/18374742/939d883c-7679-11e6-9ebd-d1469a23eda8.png">
<img width="367" alt="screen shot 2559-09-09 at 10 38 32 am" src="https://cloud.githubusercontent.com/assets/19877215/18374746/a11af6d4-7679-11e6-9558-eca378e58d0a.png">

**Comment by oopbest** [comment]
<img width="336" alt="screen shot 2559-09-09 at 12 08 00 pm" src="https://cloud.githubusercontent.com/assets/21325913/18377280/5fd674b6-7690-11e6-9033-e803eae94778.png">
<img width="346" alt="screen shot 2559-09-09 at 12 08 11 pm" src="https://cloud.githubusercontent.com/assets/21325913/18377281/5fd6c9fc-7690-11e6-8992-815890528144.png">
<img width="343" alt="screen shot 2559-09-09 at 12 08 25 pm" src="https://cloud.githubusercontent.com/assets/21325913/18377282/5fd74be8-7690-11e6-95b6-5463eaf01dbe.png">
<img width="338" alt="screen shot 2559-09-09 at 12 08 37 pm" src="https://cloud.githubusercontent.com/assets/21325913/18377279/5fd5a248-7690-11e6-9f0c-6b5782c231d1.png">
<img width="342" alt="screen shot 2559-09-09 at 12 08 49 pm" src="https://cloud.githubusercontent.com/assets/21325913/18377283/5fd7a868-7690-11e6-8e7a-f64911cdc2ca.png">
<img width="347" alt="screen shot 2559-09-09 at 12 10 12 pm" src="https://cloud.githubusercontent.com/assets/21325913/18377284/5fdbce8e-7690-11e6-8e72-6190ded0d76e.png">
<img width="344" alt="screen shot 2559-09-09 at 12 10 27 pm" src="https://cloud.githubusercontent.com/assets/21325913/18377285/6012dc9e-7690-11e6-9b45-2dfddc9a70d8.png">

**Comment by jam-krisada** [comment]
แก้ไขบน tablet แล้วเช่นกันครับ
