### ISSUE TITLE
[New Feature] ติด Tag บนรูป product ได้ (เห็นทั้งใน Gallery และ Product page)

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#7]
![image](https://cloud.githubusercontent.com/assets/20397170/17163431/770261dc-53e9-11e6-9f2f-3abe3158e766.png)

**Comment by jam-krisada** [comment]
ขั้นตอนการทำ
- สร้าง attribute code 
- เพิ่มลงไปใน attribute set 
- เพิ่ม config sql
- สร้าง field upload label image
- แสดงผลใน Product View, Catalog View
- theming

**Comment by jam-krisada** [comment]
ย้ายขึ้นไปที่ #49
