### ISSUE TITLE
Add role ไม่ได้

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#70]
กด Add role แล้วขึ้น error นี้ค่ะ
![image](https://cloud.githubusercontent.com/assets/20397170/18408753/a3b422fa-7762-11e6-8245-c402f483e01b.png)

**Comment by jam-krisada** [comment]
ดำเนินการแก้ไขให้แล้วครับ
![screen shot 2559-09-13 at 10 49 58 am](https://cloud.githubusercontent.com/assets/19877215/18461218/e4ed6e98-79a1-11e6-9d14-1eaf7c5d4720.png)
