### ISSUE TITLE
รูปใน Description ในหน้า product ยังไม่ขึ้นค่ะ

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#71]
![image](https://cloud.githubusercontent.com/assets/20397170/18460597/09632b5a-799d-11e6-922e-0e3b561376f6.png)

**Comment by jam-krisada** [comment]
@jintopvalue 
แก้ไขเรียบร้อยครับ หากรูปไหนยังไม่ขึ้นอีกแสดงว่าไม่พบรูปจริงๆครับ
http://www.topvalue.xyz/1125883912239-haier-1-muse-series-6-3-hr-cea18.html
![screen shot 2559-09-13 at 12 56 37 pm](https://cloud.githubusercontent.com/assets/19877215/18463058/89a756ba-79b1-11e6-8e19-e9eb829784df.png)
