### ISSUE TITLE
Preview Product Page 

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#78]
![image](https://cloud.githubusercontent.com/assets/20397170/18542562/c441db38-7b55-11e6-888d-c3f0f8a98e24.png)
View product สำหรับ preview ค่ะ ทีม QC ต้องใช้ในการตรวจหน้าสินค้าก่อนให้เปิดขายค่ะ

**Comment by jam-krisada** [comment]
[File]
app/design/adminhtml/default/default/template/catalog/product/edit.phtml
[change]
![screen shot 2559-09-20 at 5 21 30 pm](https://cloud.githubusercontent.com/assets/19877215/18666566/b1b95c8e-7f56-11e6-8826-cdd6549fb1e6.png)
[output]
![screen shot 2559-09-20 at 5 20 14 pm](https://cloud.githubusercontent.com/assets/19877215/18666538/862b68a0-7f56-11e6-957c-c7e130f89681.png)
