### ISSUE TITLE
รูปที่ใช้ใน Landing page ช่วงปรับปรุงระบบ

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#84]
@jam-krisada 
รูปสำหรับ Landing page ช่วงปรับปรุงระบบค่ะ
ถามหน่อยค่า นอกจากรูปแล้ว สามารถทำเป็น Text เพียวๆได้ไหมคะ
![default](https://cloud.githubusercontent.com/assets/20397170/18700461/9a76bdfe-8001-11e6-9a22-549d998542b7.png)

**Comment by jam-krisada** [comment]
@jintopvalue งงคำถามครับผม
สามารถทำเป็น Text เพียวๆได้ไหมคะ <- อธิบายเพิ่มเติมให้หน่อยครับ

ปล. เดี๋ยวจะเอารูปนี้ไปวางไว้ใน html ที่ใช้สำหรับช่วงปรับระบบครับ

**Comment by jam-krisada** [comment]
ผมทำ html แล้วครับผม
[maintenance.zip](https://github.com/topvalue/test_site/files/487053/maintenance.zip)
![screen shot 2559-09-22 at 5 52 41 pm](https://cloud.githubusercontent.com/assets/19877215/18745688/672930f2-80ed-11e6-82e4-316e10749569.png)

**Comment by jintopvalue** [comment]
@jam-krisada 
โอเคแล้วค่ะ แต่ขอเปลี่ยนเป็นรูปนี้แทนค่ะ

![- 2](https://cloud.githubusercontent.com/assets/20397170/18780922/e40af814-81a9-11e6-8bd3-32abe8e2cde6.png)

**Comment by jam-krisada** [comment]
@jintopvalue แก้ไขแล้วครับ
![screen shot 2559-09-23 at 5 50 59 pm](https://cloud.githubusercontent.com/assets/19877215/18783517/5a5afcce-81b6-11e6-8bb8-b4763a0279e4.png)
