### ISSUE TITLE
[Help] อัพโหลด CSV เพื่อยิงอัพเดท ราคาและstatus  (Enable/Disable) 

### ISSUE THREAD

**Issue by jintopvalue** [topvalue/test_site#9]
ตัวอย่างการอัพเดท Status ที่ใช้อยู่ค่ะ 
![image](https://cloud.githubusercontent.com/assets/20397170/17163615/5145c522-53eb-11e6-9629-5f68adcf584d.png)

ตัวอย่างการอัพเดทราคาที่ใช้อยู่ค่ะ 
![image](https://cloud.githubusercontent.com/assets/20397170/17163610/3b9fbc00-53eb-11e6-8924-2d8cbd5535cb.png)

**Comment by jam-krisada** [comment]
ระบบยิงอัพเดทสินค้า
http://www.topvalue.xyz/magmi/web/magmi.php
User: marvelic
Pass: marvelic01

1. นำไฟล์​ csv ตัวอย่าง columns คือ (sku,price,special_price,status) sku จำเป็นต้องใส่เสมอ อัพโหลเข้าไปยัง ~/var/import
![screen shot 2559-07-27 at 7 15 12 pm](https://cloud.githubusercontent.com/assets/19877215/17174840/7a885506-542e-11e6-8fad-72cea0de73a6.png)

2. เลือกไฟล์ที่พึ่งอัพขึ้นระบบ
![screen shot 2559-07-27 at 7 14 45 pm](https://cloud.githubusercontent.com/assets/19877215/17175005/59da1334-542f-11e6-9686-69ef0a661852.png)

3. กด run import
![screen shot 2559-07-27 at 7 28 05 pm](https://cloud.githubusercontent.com/assets/19877215/17175195/47bcd884-5430-11e6-8345-0e1bd38d8533.png)

solved #9 @joomlacorner

**Comment by jintopvalue** [comment]
columns ในไฟล์ที่อัพโหลด ต้องใส่ครบทุกอันไหมคะ (price,special_price,status)
เช่น ถ้าอยากจะปรับราคา ต้องใส่ status ไหมคะ
และถ้าอยากจะปรับ status ก็ไม่ต้องใส่ price,special_price ใช่ไหมคะ

**Comment by jam-krisada** [comment]
@jintopvalue ไม่จำเป็นต้องใส่ทุกช่องครับ ส่วนที่บังคับใส่คือ sku เท่านั้นครับ

**Comment by jintopvalue** [comment]
@jam-krisada 
หลังจากยิงแล้ว ราคากับ status จะมีผลทันทีหรือเปล่าคะ?

**Comment by jam-krisada** [comment]
@jintopvalue Magmi ยิงเข้าฐานข้อมูลทันทีครับ การแสดงผลขึ้นอยู่กับระบบ cache ที่เปิดใช้งานอยู่ กับระบบจัดการ index ของตัว Magento ต้องกด Fetch Index ใหม่เพื่อให้การแสดงผล

**Comment by jintopvalue** [comment]
@jam-krisada 
ทางทีมลงสินค้าอยากจะทดลองใช้งานดูน่ะค่ะ ไม่ทราบว่าสามารถให้ Host, Port, Key File ของ .xyz เพื่อให้เข้าไปทดสอบได้ไหมคะ ถ้าไม่สะดวก อัพโหลดขึ้น valley.topvalue.com ก็ได้ค่ะ 
![image](https://cloud.githubusercontent.com/assets/20397170/17393350/570d408a-5a4d-11e6-881f-b232cccc072c.png)

**Comment by jam-krisada** [comment]
@jintopvalue กำลังดำเนินการสร้าง FTP Account สำหรับ ใช้งาน folder var/import ให้ครับ

**Comment by jam-krisada** [comment]
@jintopvalue ข้อมูลการเชื่อมต่อ FTP ครับ เพื่อเข้าไปวางไฟล์ในเว็บไซต์ topvalue.xyz
Host : 103.40.117.121
Username : importftp@topvalue.xyz
Password : <สอบถาม @joomlacorner>
Path : /home/devtopv/public_html/var/import
Port : 21

**Comment by jintopvalue** [comment]
@jam-krisada 
รบกวนหน่อยค่ะ ทีมลงสินค้าบอกว่าเข้าต่อไม่ได้ค่ะ 
![image](https://cloud.githubusercontent.com/assets/20397170/17396001/59e4c824-5a5b-11e6-8f7a-cb0801e7a910.png)

**Comment by jam-krisada** [comment]
@jintopvalue สามารถวางไฟล์ใน Folder ที่เห็นได้เลยครับ
![screen shot 2559-08-04 at 3 53 05 pm](https://cloud.githubusercontent.com/assets/19877215/17396053/a3076c82-5a5b-11e6-81ee-8ff163190601.png)

**Comment by jintopvalue** [comment]
@jam-krisada ถามหน่อยค่า ต้องเลือกอันไหนเหรอคะ
![image](https://cloud.githubusercontent.com/assets/20397170/17397646/3832baa8-5a63-11e6-92e1-6bf146be56a5.png)

**Comment by jam-krisada** [comment]
@jintopvalue กดมาจากตรงไหนนะครับ หน้านี้ผมไม่เคยใช้งานเลยครับ
refresh หน้านี้ใหม่ไหมครับ

**Comment by jintopvalue** [comment]
@jam-krisada ขึ้นมาหลังกด run import ค่ะ เดี๋ยวให้เขาลอง refresh ดูนะคะ

**Comment by jam-krisada** [comment]
@jintopvalue ถ้าเจออีกครั้ง กด Run with selected option ได้เลยครับ

**Comment by jam-krisada** [comment]
@jintopvalue Final วิธีอัพเดทข้อมูลครั้งละมากๆ
ขั้นตอนการอัพเดทข้อมูลบนระบบ topvalue ด้วย Import Profiler เนื่องจากการ import ด้วยวิธีการนี้จะเรียก Function Model ของระบบ Magento ทำให้วิ่งไป อัพเดทข้อมูลบน ERP ด้วย

1. อัพโหลดไฟล์ csv ที่ต้องการไว้ใน var/import ด้วย FTP Client
<img width="753" alt="screen shot 2559-09-03 at 4 21 40 pm" src="https://cloud.githubusercontent.com/assets/19877215/18224025/8b5fe6dc-71f2-11e6-970e-6a16fc488386.png">

2. เข้าไปที่ System -> Import/Export -> Dataflow - Profiles
<img width="297" alt="screen shot 2559-09-03 at 4 16 36 pm" src="https://cloud.githubusercontent.com/assets/19877215/18223986/d1665c70-71f1-11e6-8b8a-44401464dede.png">

3. เลือกไฟล์และกด Run Profile 
<img width="737" alt="screen shot 2559-09-03 at 4 23 15 pm" src="https://cloud.githubusercontent.com/assets/19877215/18224036/c337257a-71f2-11e6-9eb5-c5ac73377c66.png">

4. หน้าแสดงผลการ import ข้อมูล
<img width="553" alt="screen shot 2559-09-03 at 4 26 36 pm" src="https://cloud.githubusercontent.com/assets/19877215/18224054/4538b660-71f3-11e6-9639-f5f5fd0086cb.png">

5. เช็คผลลัพธ์ในการ sync ไปยัง ERP
<img width="1192" alt="screen shot 2559-09-03 at 4 33 17 pm" src="https://cloud.githubusercontent.com/assets/19877215/18224083/50fbba82-71f4-11e6-9509-b52de62d1382.png">

**Comment by jintopvalue** [comment]
@jam-krisada 
![image](https://cloud.githubusercontent.com/assets/20397170/18577031/f281b0f2-7c10-11e6-87f2-42cbc5d1229f.png)

Store หมายถึงอะไรเหรอคะ 
แล้วจำเป็นต้องใส่ชื่อสินค้าด้วยเหรอคะ (name)

**Comment by jam-krisada** [comment]
@jintopvalue ใช้เหมือนที่เคยเพิ่มรูปตัวอย่างไว้ใน comment แรกครับ
อันนี้เอามาจากไหนหรือครับ?

**Comment by jintopvalue** [comment]
@jam-krisada 
เป็นไฟล์ที่เคยอยู่ใร import ค่ะ แต่ตอนนี้หาไม่เจอแล้วค่ะ ไม่เป็นไรค่ะ เดี๋ยวใช้ไฟล์เดิมค่ะ

**Comment by jintopvalue** [comment]
@jam-krisada format ไฟล์ที่ใช้อัพโหลดผ่าน import profiler ใช้ format เดิมได้เลยใช่ไหมคะ

**Comment by jam-krisada** [comment]
@jintopvalue ใช้รูปแบบเดิมครับ แต่ต้องเปลี่ยน SKU ให้ตรงกับ .xyz ครับ
